/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.arquivo;

import conexoes.ConexaoMySQL;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ferna
 */
public class Cons_Capa extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cons_Arquivo
     */
    public Cons_Capa() {
        initComponents();
        this.listaAssuntos();

    }

    ConexaoMySQL cn = new ConexaoMySQL();
    String url;
    String driver = "com.mysql.jdbc.Driver";
    String usuario;
    String senha;

    DateFormat dateOut = new SimpleDateFormat("yyyy/MM/dd");
    DateFormat dateIn = new SimpleDateFormat("dd/MM/yyyy");

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void DadosConexao() {
        try (FileReader arq = new FileReader("conexao.txt")) {
            BufferedReader lerArq = new BufferedReader(arq);
            String linha = lerArq.readLine();
            int line = 1;
            while (linha != null) {
                switch (line) {
                    case 1:
                        url = "jdbc:mysql://" + linha;
                        break;
                    case 2:
                        usuario = linha;
                        break;
                    case 3:
                        senha = linha;
                        break;
                    default:
                        break;
                }
                line++;
                linha = lerArq.readLine();
            }
            arq.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Erro na abertura do arquivo: " + e);

        }
    }

    public void listaAssuntos() {
        String sql = "SELECT * FROM cad_arquivo_assuntos "
                + "order by descricao";

        cn.conecta();
        cn.executeConsulta(sql);
        try {
            while (cn.rs.next()) {
                jCbAssuntos.addItem(cn.rs.getString(2));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cons_Capa.class.getName()).log(Level.SEVERE, null, ex);
        }
        cn.desconecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCbAssuntos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSpData = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblPastas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTxtObs = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        setClosable(true);
        setTitle("Consulta de capas");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Assunto");

        jCbAssuntos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Data");

        jSpData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpData.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        jSpData.setEditor(new javax.swing.JSpinner.DateEditor(jSpData, "dd/MM/yyyy"));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setMnemonic('P');
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTblPastas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTblPastas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTblPastas);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Obs.:");

        jTxtObs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jCheckBox1.setText("Todos os assuntos");

        jCheckBox2.setText("Todas as datas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1108, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCbAssuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtObs)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSpData, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(jCheckBox2))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCbAssuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jSpData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel3)
                    .addComponent(jTxtObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String assunto = jCbAssuntos.getSelectedItem().toString();
        String data = dateOut.format(jSpData.getValue());
        String obs = jTxtObs.getText();
        String condicaoObs = "";
        String periodo = "AND data_inicial <= '" + data + "' AND data_final >= '" + data + "'";
        String condicaoAssunto = " AND nome_assunto ='" + assunto + "' ";
        String estante;

        if (!"".equals(obs)) {
            condicaoObs = "AND UPPER(observacao) LIKE '%" + obs.toUpperCase() + "%' ";
        }

        if (jCheckBox1.isSelected()) {
            condicaoAssunto = "";
        }

        if (jCheckBox2.isSelected()) {
            periodo = "";
        }

        String sql = "SELECT DISTINCT id_capa as id,nome_assunto,nome_empresa,"
                + "nome_estabelecimento,data_inicial,data_final,observacao,id_empresa,"
                + "nome_local,estante,prateleira,sequencia "
                + "FROM rel_arquivo_pastas WHERE id_empresa IS NOT NULL "
                + condicaoAssunto
                + condicaoObs
                + periodo + " "
                + "ORDER BY nome_assunto, data_inicial;";

        DefaultTableModel pastas = (DefaultTableModel) jTblPastas.getModel();
        pastas.setColumnCount(0);
        pastas.setRowCount(0);

        pastas.addColumn("Emp.");
        pastas.addColumn("Unidade");
        pastas.addColumn("Caixa");
        pastas.addColumn("Capa");
        pastas.addColumn("Assunto");
        pastas.addColumn("Início");
        pastas.addColumn("Fim");
        pastas.addColumn("Observação");
        pastas.addColumn("Local");

        jTblPastas.getColumnModel().getColumn(0).setMaxWidth(50);
        jTblPastas.getColumnModel().getColumn(0).setMinWidth(50);
        jTblPastas.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(50);
        jTblPastas.getTableHeader().getColumnModel().getColumn(0).setMinWidth(50);
        jTblPastas.getColumnModel().getColumn(2).setMaxWidth(50);
        jTblPastas.getColumnModel().getColumn(2).setMinWidth(50);
        jTblPastas.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(50);
        jTblPastas.getTableHeader().getColumnModel().getColumn(2).setMinWidth(50);
        jTblPastas.getColumnModel().getColumn(3).setMaxWidth(50);
        jTblPastas.getColumnModel().getColumn(3).setMinWidth(50);
        jTblPastas.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(50);
        jTblPastas.getTableHeader().getColumnModel().getColumn(3).setMinWidth(50);
        jTblPastas.getColumnModel().getColumn(5).setMaxWidth(100);
        jTblPastas.getColumnModel().getColumn(5).setMinWidth(100);
        jTblPastas.getTableHeader().getColumnModel().getColumn(5).setMaxWidth(100);
        jTblPastas.getTableHeader().getColumnModel().getColumn(5).setMinWidth(100);
        jTblPastas.getColumnModel().getColumn(6).setMaxWidth(100);
        jTblPastas.getColumnModel().getColumn(6).setMinWidth(100);
        jTblPastas.getTableHeader().getColumnModel().getColumn(6).setMaxWidth(100);
        jTblPastas.getTableHeader().getColumnModel().getColumn(6).setMinWidth(100);

        cn.conecta();

        try {
            cn.executeConsulta(sql);
            while (cn.rs.next()) {

                if ((cn.rs.getString("estante") != null)
                        && (cn.rs.getString("prateleira")) != null) {
                    estante = ", E: " + cn.rs.getString("estante") + ", P: " + cn.rs.getString("prateleira");
                } else {
                    estante = "";
                }

                pastas.addRow(new String[]{
                    cn.rs.getString("id_empresa"),
                    cn.rs.getString(4),
                    cn.rs.getString("sequencia"),
                    cn.rs.getString(1),
                    cn.rs.getString("nome_assunto"),
                    dateIn.format(cn.rs.getDate(5)),
                    dateIn.format(cn.rs.getDate(6)),
                    cn.rs.getString("observacao"),
                    cn.rs.getString("nome_local") + estante
                });
            }
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
        }

        cn.desconecta();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCbAssuntos;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpData;
    private javax.swing.JTable jTblPastas;
    private javax.swing.JTextField jTxtObs;
    // End of variables declaration//GEN-END:variables
}
