/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.arquivo;

import conexoes.ConexaoMySQL;
import java.awt.Dimension;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ferna
 */
public class Cons_Arquivo extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cons_Arquivo
     */
    public Cons_Arquivo() {
        initComponents();
        this.listaAssuntos();

    }

    ConexaoMySQL cn = new ConexaoMySQL();

    DateFormat dateOut = new SimpleDateFormat("yyyy/MM/dd");

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void listaAssuntos() {
        String sql = "SELECT * FROM cad_arquivo_assuntos "
                + "order by descricao";

        cn.conecta();
        cn.executeConsulta(sql);
        try {
            while (cn.rs.next()) {
                jCbAssuntos.addItem(cn.rs.getString(2));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cons_Arquivo.class.getName()).log(Level.SEVERE, null, ex);
        }
        cn.desconecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCbAssuntos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSpData = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblPastas = new javax.swing.JTable();

        setClosable(true);
        setTitle("Consulta Arquivo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Assunto");

        jCbAssuntos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Data");

        jSpData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpData.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        jSpData.setEditor(new javax.swing.JSpinner.DateEditor(jSpData, "dd/MM/yyyy"));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setMnemonic('P');
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTblPastas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTblPastas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTblPastas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCbAssuntos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpData, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCbAssuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jSpData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String assunto = jCbAssuntos.getSelectedItem().toString();
        String data = dateOut.format(jSpData.getValue());
        String estante;

        String sql = "SELECT DISTINCT sequencia,nome_assunto,nome_empresa,"
                + "nome_estabelecimento,nome_tipo,nome_local,estante,prateleira "
                + "FROM rel_arquivo_pastas "
                + "WHERE nome_assunto ='" + assunto + "' "
                + "AND data_inicial <= '" + data + "' "
                + "AND data_final >= '" + data + "'";

        DefaultTableModel pastas = (DefaultTableModel) jTblPastas.getModel();
        pastas.setColumnCount(0);
        pastas.setRowCount(0);

        //pastas.addColumn("Empresa");
        pastas.addColumn("Unidade");
        pastas.addColumn("Caixa");
        //pastas.addColumn("Assunto");
        pastas.addColumn("Tipo Arquivo");
        pastas.addColumn("Local");

        jTblPastas.getColumnModel().getColumn(1).setMaxWidth(50);
        jTblPastas.getColumnModel().getColumn(1).setMinWidth(50);
        jTblPastas.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(50);
        jTblPastas.getTableHeader().getColumnModel().getColumn(1).setMinWidth(50);

        cn.conecta();
        cn.executeConsulta(sql);

        try {
            while (cn.rs.next()) {

                if ((cn.rs.getString("estante") != null)
                        && (cn.rs.getString("prateleira")) != null) {
                    estante = ", E: " + cn.rs.getString("estante") + ", P: " + cn.rs.getString("prateleira");
                } else {
                    estante = "";
                }

                pastas.addRow(new String[]{
                    //cn.rs.getString(12),
                    cn.rs.getString(4),
                    cn.rs.getString(1),
                    //cn.rs.getString(6),
                    cn.rs.getString(5),
                    cn.rs.getString("nome_local") + estante
                });
            }
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
        }

        cn.desconecta();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCbAssuntos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpData;
    private javax.swing.JTable jTblPastas;
    // End of variables declaration//GEN-END:variables
}
