/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.arquivo;

import conexoes.ConexaoMySQL;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author luiz.barcellos
 */
public class UtilAlteraAssuntos extends javax.swing.JInternalFrame {

    /**
     * Creates new form UtilAlteraAssuntos
     */
    ConexaoMySQL cn = new ConexaoMySQL();
    String url;
    String driver = "com.mysql.jdbc.Driver";
    String usuario;
    String senha;

    public UtilAlteraAssuntos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtContarCapas = new javax.swing.JTextField();
        jTxtIdAssunto = new javax.swing.JTextField();
        jTxtNomeAssunto = new javax.swing.JTextField();
        jBtnProcessar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Alterar assuntos nas capas");

        jLabel1.setText("Assunto");

        jLabel2.setText("Quantidade de capas");

        jTxtContarCapas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtContarCapas.setEnabled(false);

        jTxtIdAssunto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtIdAssuntoKeyReleased(evt);
            }
        });

        jTxtNomeAssunto.setEnabled(false);

        jBtnProcessar.setText("Processar");
        jBtnProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProcessarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTxtContarCapas, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnProcessar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTxtIdAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNomeAssunto)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtIdAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtContarCapas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnProcessar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtIdAssuntoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtIdAssuntoKeyReleased
        String id = jTxtIdAssunto.getText();
        jTxtNomeAssunto.setText("");
        jTxtContarCapas.setText("");

        String sql = "SELECT * FROM cad_arquivo_assuntos "
                + "WHERE id = '" + id + "';";

        
        cn.conecta();
        cn.executeConsulta(sql);
        try {
            while (cn.rs.next()) {
                jTxtNomeAssunto.setText(cn.rs.getString("descricao"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(UtilAlteraAssuntos.class.getName()).log(Level.SEVERE, null, ex);
        }
        cn.desconecta();

        if (!"".equals(jTxtNomeAssunto.getText())) {
            String contagem = "SELECT COUNT(id) as id from cad_arquivo_capas "
                    + "WHERE id_assunto = '" + id + "';";
            cn.conecta();
            cn.executeConsulta(contagem);
            try {
                while (cn.rs.next()) {
                    jTxtContarCapas.setText(cn.rs.getString("id"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(UtilAlteraAssuntos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jTxtIdAssuntoKeyReleased

    private void jBtnProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProcessarActionPerformed
        String nome_assunto = jTxtNomeAssunto.getText();
        String id = jTxtIdAssunto.getText();

        if (!"".equals(nome_assunto)) {
            int resposta = JOptionPane.showInternalConfirmDialog(this, "Deseja realmente alterar o nome dos assuntos?", null, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            switch (resposta) {
                case 0:
                    String sql = "UPDATE cad_arquivo_capas set nome_assunto = '" + nome_assunto + "' "
                            + "WHERE id_assunto = '" + id + "';";
                    String sql2 = "UPDATE cad_arquivo_pastas_detalhe set nome_assunto = '" + nome_assunto + "' "
                            + "WHERE id_assunto = '" + id + "';";
                    cn.conecta();
                    try {
                        cn.executeAtualizacao(sql);
                        cn.executeAtualizacao(sql2);
                        JOptionPane.showMessageDialog(this, "Atualização executada com sucesso!");
                        jTxtIdAssunto.setText("");
                        jTxtNomeAssunto.setText("");
                        jTxtContarCapas.setText("");

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Não foi possível alterar o nome dos assuntos! Erro :" + e);
                    }
                    cn.desconecta();
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Nenhuma capa foi alterada!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "O assunto não foi definido!");
        }
    }//GEN-LAST:event_jBtnProcessarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnProcessar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtContarCapas;
    private javax.swing.JTextField jTxtIdAssunto;
    private javax.swing.JTextField jTxtNomeAssunto;
    // End of variables declaration//GEN-END:variables

    public void DadosConexao() {
        try (FileReader arq = new FileReader("conexao.txt")) {
            BufferedReader lerArq = new BufferedReader(arq);
            String linha = lerArq.readLine();
            int line = 1;
            while (linha != null) {
                switch (line) {
                    case 1:
                        url = "jdbc:mysql://" + linha;
                        break;
                    case 2:
                        usuario = linha;
                        break;
                    case 3:
                        senha = linha;
                        break;
                    default:
                        break;
                }
                line++;
                linha = lerArq.readLine();
            }
            arq.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Erro na abertura do arquivo: " + e);

        }
    }

}
