/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luiz.barcellos
 */
public class Cad_prazo extends javax.swing.JInternalFrame {

    ConexaoMySQL cn = new ConexaoMySQL();
    private int var_consulta;

    DateFormat dateOut = new SimpleDateFormat("yyyy/MM/dd");
    DateFormat dateIn = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form Cad_prazo
     */
    public Cad_prazo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPesquisar = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jTxtPesquisa_Multi = new javax.swing.JTextField();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTblConsulta_Multi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtIdObrigação = new javax.swing.JTextField();
        jTxtNomeObrigacao = new javax.swing.JTextField();
        jBtnPesquisaObrigacao = new javax.swing.JButton();
        jTxtIdEstabelecimento = new javax.swing.JTextField();
        jTxtNomeEmpresa = new javax.swing.JTextField();
        jBtnPesquisaEstab = new javax.swing.JButton();
        jTxtId = new javax.swing.JTextField();
        jBtnPesquisar = new javax.swing.JButton();
        jTxtProtocolo = new javax.swing.JTextField();
        jSpSolicitacao = new javax.swing.JSpinner();
        jSpVencimento = new javax.swing.JSpinner();
        jTxtObs = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtId1 = new javax.swing.JTextField();
        jBtnPesquisar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnGravar = new javax.swing.JButton();

        jPesquisar.setTitle("Pesquisar");
        jPesquisar.setMinimumSize(new java.awt.Dimension(700, 400));

        jTxtPesquisa_Multi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtPesquisa_Multi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtPesquisa_MultiKeyReleased(evt);
            }
        });

        jBtnConfirmar.setText("Adicionar");
        jBtnConfirmar.setEnabled(false);
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jTblConsulta_Multi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTblConsulta_Multi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblConsulta_Multi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblConsulta_MultiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTblConsulta_MultiMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(jTblConsulta_Multi);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 453, Short.MAX_VALUE)
                        .addComponent(jBtnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnConfirmar))
                    .addComponent(jTxtPesquisa_Multi)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTxtPesquisa_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPesquisarLayout = new javax.swing.GroupLayout(jPesquisar.getContentPane());
        jPesquisar.getContentPane().setLayout(jPesquisarLayout);
        jPesquisarLayout.setHorizontalGroup(
            jPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPesquisarLayout.setVerticalGroup(
            jPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Controle de prazos");

        jLabel1.setText("Código");

        jLabel2.setText("Obrigação");

        jLabel3.setText("Empresa");

        jLabel4.setText("Data da Solicitação");

        jLabel5.setText("Protocolo");

        jLabel6.setText("Vencimento");

        jTxtIdObrigação.setEnabled(false);
        jTxtIdObrigação.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdObrigaçãoFocusLost(evt);
            }
        });

        jTxtNomeObrigacao.setEnabled(false);

        jBtnPesquisaObrigacao.setText("...");
        jBtnPesquisaObrigacao.setEnabled(false);
        jBtnPesquisaObrigacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisaObrigacaoActionPerformed(evt);
            }
        });

        jTxtIdEstabelecimento.setEnabled(false);
        jTxtIdEstabelecimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdEstabelecimentoFocusLost(evt);
            }
        });

        jTxtNomeEmpresa.setEnabled(false);

        jBtnPesquisaEstab.setText("...");
        jBtnPesquisaEstab.setEnabled(false);
        jBtnPesquisaEstab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisaEstabActionPerformed(evt);
            }
        });

        jTxtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdFocusLost(evt);
            }
        });

        jBtnPesquisar.setText("...");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jTxtProtocolo.setEnabled(false);

        jSpSolicitacao.setModel(new javax.swing.SpinnerDateModel());
        jSpSolicitacao.setEditor(new javax.swing.JSpinner.DateEditor(jSpSolicitacao, "dd/MM/yyyy"));
        jSpSolicitacao.setEnabled(false);

        jSpVencimento.setModel(new javax.swing.SpinnerDateModel());
        jSpVencimento.setEditor(new javax.swing.JSpinner.DateEditor(jSpVencimento, "dd/MM/yyyy"));
        jSpVencimento.setEnabled(false);

        jTxtObs.setEnabled(false);

        jLabel7.setText("Obs");

        jLabel8.setText("Prazo Anterior");

        jTxtId1.setEnabled(false);
        jTxtId1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtId1FocusLost(evt);
            }
        });

        jBtnPesquisar1.setText("...");
        jBtnPesquisar1.setEnabled(false);
        jBtnPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtIdObrigação, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jTxtId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtId1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar1)
                        .addGap(354, 354, 354))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTxtProtocolo)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTxtIdEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTxtNomeObrigacao, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnPesquisaObrigacao)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpSolicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTxtNomeEmpresa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnPesquisaEstab))))
                            .addComponent(jTxtObs))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesquisar)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnPesquisar1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtIdObrigação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeObrigacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesquisaObrigacao)
                    .addComponent(jLabel4)
                    .addComponent(jSpSolicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtIdEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesquisaEstab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jTxtProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnEditar.setText("Editar");
        jBtnEditar.setEnabled(false);
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        jBtnGravar.setText("Gravar");
        jBtnGravar.setEnabled(false);
        jBtnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnGravar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        if ("Incluir".equals(jBtnIncluir.getText())) {
            jBtnIncluir.setText("Cancelar");
            jTxtId.setText("NOVO");
            jBtnEditar.setEnabled(false);
            habilitarEdicao();
        } else {
            desabilitarEdicao();
            limpaCampos();
        }
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        if ("Editar".equals(jBtnEditar.getText())) {
            jBtnEditar.setText("Cancelar");
            habilitarEdicao();

            jBtnIncluir.setEnabled(false);

        } else {
            desabilitarEdicao();
        }
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jBtnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGravarActionPerformed
        String id = jTxtId.getText();
        String obrigacao = jTxtIdObrigação.getText();
        String empresa = jTxtIdEstabelecimento.getText();
        String obs = jTxtObs.getText();
        String protocolo = jTxtProtocolo.getText();
        String dt_sol = dateOut.format(jSpSolicitacao.getValue());
        String dt_venc = dateOut.format(jSpVencimento.getValue());
        int usuario = TelaInicial.usuariosys;

        String sql;

        cn.conecta();
        if ("Cancelar".equals(jBtnIncluir.getText())) {
            cn.executeConsulta("show table status like 'cad_prazos';");
            try {
                while (cn.rs.next()) {
                    id = cn.rs.getString("auto_increment");
                }
                cn.rs.close();
            } catch (SQLException ex) {
                ConexaoMySQL.resultadoUpd = 2;
                JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
            }

            sql = "INSERT INTO cad_prazos (id_obrigacao, id_estabelecimento, "
                    + "protocolo, dt_solicitacao, dt_vencimento, obs, usu_inc, dt_inc) "
                    + "VALUES (" + obrigacao + "," + empresa + ",'" + protocolo + "',"
                    + "'" + dt_sol + "','" + dt_venc + "','" + obs + "'," + usuario + ", current_date());";
        } else {
            sql = "UPDATE cad_prazos set id_obrigacao = " + obrigacao + ", "
                    + "id_estabelecimento = " + empresa + ", "
                    + "protocolo = '" + protocolo + "', dt_solicitacao = '" + dt_sol + "', "
                    + "dt_vencimento = '" + dt_venc + "', obs = '" + obs + "', "
                    + "usu_alt = " + usuario + ", dt_alt = current_date() "
                    + "WHERE id = " + id + "; ";
        }
        cn.executeAtualizacao(sql);
        cn.desconecta();

        if (ConexaoMySQL.resultadoUpd < 1) {
            desabilitarEdicao();
            jTxtId.setText(id);
        }
    }//GEN-LAST:event_jBtnGravarActionPerformed

    private void jTxtPesquisa_MultiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPesquisa_MultiKeyReleased
        montaLista();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPesquisa_MultiKeyReleased

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        IncluiPesquisa();
        jPesquisar.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        jPesquisar.setVisible(false);        // TODO add your handling code here:
        jPesquisar.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTblConsulta_MultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseClicked
        jBtnConfirmar.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jTblConsulta_MultiMouseClicked

    private void jTblConsulta_MultiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTblConsulta_MultiMouseEntered

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        var_consulta = 1;

        jPesquisar.setVisible(true);

        montaLista();
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnPesquisaObrigacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisaObrigacaoActionPerformed
        var_consulta = 2;

        jPesquisar.setVisible(true);

        montaLista();
    }//GEN-LAST:event_jBtnPesquisaObrigacaoActionPerformed

    private void jBtnPesquisaEstabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisaEstabActionPerformed
        var_consulta = 3;

        jPesquisar.setVisible(true);

        montaLista();
    }//GEN-LAST:event_jBtnPesquisaEstabActionPerformed

    private void jTxtIdObrigaçãoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdObrigaçãoFocusLost
        jTxtNomeObrigacao.setText("");

        if (!"".equals(jTxtIdObrigação.getText())) {
            var_consulta = 22;
            IncluiPesquisa();
        }

    }//GEN-LAST:event_jTxtIdObrigaçãoFocusLost

    private void jTxtIdEstabelecimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdEstabelecimentoFocusLost
        jTxtNomeEmpresa.setText("");

        if (!"".equals(jTxtIdEstabelecimento.getText())) {
            var_consulta = 33;
            IncluiPesquisa();
        }
    }//GEN-LAST:event_jTxtIdEstabelecimentoFocusLost

    private void jTxtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdFocusLost
        String id = jTxtId.getText();
        limpaCampos();
        jTxtId.setText(id);

        if (!"".equals(jTxtId.getText())) {
            var_consulta = 11;
            IncluiPesquisa();
        }

        if (!"".equals(jTxtNomeObrigacao.getText())) {
            jBtnEditar.setEnabled(true);
        } else {
            jBtnEditar.setEnabled(false);
        }
    }//GEN-LAST:event_jTxtIdFocusLost

    private void jTxtId1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtId1FocusLost
        String id = jTxtId1.getText();
        limpaCampos();
        jTxtId1.setText(id);

        if (!"".equals(jTxtId1.getText())) {
            var_consulta = 44;
            IncluiPesquisa();
        }
    }//GEN-LAST:event_jTxtId1FocusLost

    private void jBtnPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisar1ActionPerformed
        var_consulta = 4;

        jPesquisar.setVisible(true);

        montaLista();
    }//GEN-LAST:event_jBtnPesquisar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnGravar;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisaEstab;
    private javax.swing.JButton jBtnPesquisaObrigacao;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JButton jBtnPesquisar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JFrame jPesquisar;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpSolicitacao;
    private javax.swing.JSpinner jSpVencimento;
    private javax.swing.JTable jTblConsulta_Multi;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtId1;
    private javax.swing.JTextField jTxtIdEstabelecimento;
    private javax.swing.JTextField jTxtIdObrigação;
    private javax.swing.JTextField jTxtNomeEmpresa;
    private javax.swing.JTextField jTxtNomeObrigacao;
    private javax.swing.JTextField jTxtObs;
    private javax.swing.JTextField jTxtPesquisa_Multi;
    private javax.swing.JTextField jTxtProtocolo;
    // End of variables declaration//GEN-END:variables

    private void habilitarEdicao() {
        jTxtId.setEnabled(false);
        jTxtIdObrigação.setEnabled(true);
        jTxtIdEstabelecimento.setEnabled(true);
        jTxtProtocolo.setEnabled(true);
        jTxtObs.setEnabled(true);
        jTxtId1.setEnabled(true);

        jSpVencimento.setEnabled(true);
        jSpSolicitacao.setEnabled(true);

        jBtnPesquisar.setEnabled(false);
        jBtnPesquisaEstab.setEnabled(true);
        jBtnPesquisaObrigacao.setEnabled(true);
        jBtnPesquisar1.setEnabled(true);

        jBtnGravar.setEnabled(true);
    }

    private void desabilitarEdicao() {
        jTxtId.setEnabled(true);
        jTxtIdObrigação.setEnabled(false);
        jTxtIdEstabelecimento.setEnabled(false);
        jTxtProtocolo.setEnabled(false);
        jTxtObs.setEnabled(false);
        jTxtId1.setEnabled(false);

        jSpVencimento.setEnabled(false);
        jSpSolicitacao.setEnabled(false);

        jBtnPesquisar.setEnabled(true);
        jBtnPesquisaEstab.setEnabled(false);
        jBtnPesquisaObrigacao.setEnabled(false);
        jBtnIncluir.setEnabled(true);
        jBtnEditar.setEnabled(false);
        jBtnPesquisar1.setEnabled(false);

        jBtnGravar.setEnabled(false);

        jBtnEditar.setText("Editar");
        jBtnIncluir.setText("Incluir");
    }

    private void limpaCampos() {
        jTxtId.setText("");
        jTxtId1.setText("");
        jTxtIdObrigação.setText("");
        jTxtNomeObrigacao.setText("");
        jTxtIdEstabelecimento.setText("");
        jTxtNomeEmpresa.setText("");
        jTxtProtocolo.setText("");
        jTxtObs.setText("");
    }

    private void IncluiPesquisa() {

        int linha = jTblConsulta_Multi.getSelectedRow();

        String id;
        String sql;

        switch (var_consulta) {
            case 1:
                jTxtId.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());

            case 11:

                id = jTxtId.getText();
                sql = "SELECT * FROM cad_prazos WHERE id = " + id;
                cn.conecta();
                cn.executeConsulta(sql);
                try {
                    while (cn.rs.next()) {

                        String dts = dateIn.format(cn.rs.getObject("dt_solicitacao"));
                        String dtv = dateIn.format(cn.rs.getObject("dt_vencimento"));

                        jTxtIdObrigação.setText(cn.rs.getString("id_obrigacao"));
                        jTxtIdEstabelecimento.setText(cn.rs.getString("id_estabelecimento"));
                        jTxtProtocolo.setText(cn.rs.getString("protocolo"));
                        jTxtObs.setText(cn.rs.getString("obs"));
                        jSpSolicitacao.setValue(dateIn.parse(dts));
                        jSpVencimento.setValue(dateIn.parse(dtv));
                    }
                } catch (Exception ex) {

                    JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                }
                cn.desconecta();

                if (!"".equals(jTxtIdEstabelecimento.getText())
                        && !"".equals(jTxtIdObrigação.getText())) {

                    var_consulta = 22;
                    IncluiPesquisa();
                    var_consulta = 33;
                    IncluiPesquisa();
                }

                break;

            case 2:

                jTxtIdObrigação.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());

            case 22:
                id = jTxtIdObrigação.getText();
                sql = "SELECT * FROM cad_prazos_tipos WHERE id = " + id;

                cn.conecta();
                cn.executeConsulta(sql);
                try {
                    while (cn.rs.next()) {
                        jTxtNomeObrigacao.setText(cn.rs.getString("descricao"));
                    }
                } catch (SQLException ex) {

                    JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                }
                cn.desconecta();

                break;

            case 3:
                jTxtIdEstabelecimento.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());
            case 33:
                id = jTxtIdEstabelecimento.getText();
                sql = "SELECT a.id, a.razao_social, b.nome, a.inscricao_federal "
                        + "FROM cad_estabelecimentos a "
                        + "LEFT JOIN cad_empresas b on (b.id = a.id_empresa) "
                        + "WHERE a.id = " + id;

                cn.conecta();
                cn.executeConsulta(sql);
                try {
                    while (cn.rs.next()) {
                        jTxtNomeEmpresa.setText(cn.rs.getString("razao_social")
                                + " (" + cn.rs.getString("nome") + ")");
                    }
                } catch (SQLException ex) {

                    JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                }
                cn.desconecta();
                break;

            case 4:

                jTxtId1.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());

            case 44:
                id = jTxtId1.getText();
                sql = "SELECT * FROM cad_prazos WHERE id = " + id;
                cn.conecta();
                cn.executeConsulta(sql);
                try {
                    while (cn.rs.next()) {

                        jTxtIdObrigação.setText(cn.rs.getString("id_obrigacao"));
                        jTxtIdEstabelecimento.setText(cn.rs.getString("id_estabelecimento"));
                    }
                } catch (Exception ex) {

                    JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                }
                cn.desconecta();

                if (!"".equals(jTxtIdEstabelecimento.getText())
                        && !"".equals(jTxtIdObrigação.getText())) {

                    var_consulta = 22;
                    IncluiPesquisa();
                    var_consulta = 33;
                    IncluiPesquisa();
                }

        }
    }

    private void montaLista() {
        DefaultTableModel lista = (DefaultTableModel) jTblConsulta_Multi.getModel();
        jTxtPesquisa_Multi.grabFocus();

        lista.setColumnCount(0);
        lista.setRowCount(0);

        String sql;
        String id;
        String condicao;

        switch (var_consulta) {
            case 1:

                lista.addColumn("Id");
                lista.addColumn("Obrigação");
                lista.addColumn("Protocolo");
                lista.addColumn("Empresa");
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(60);

                if (!"".equals(jTxtPesquisa_Multi.getText())) {
                    condicao = "WHERE UPPER(c.razao_social) "
                            + "LIKE '%" + jTxtPesquisa_Multi.getText().toUpperCase() + "%' "
                            + "OR UPPER(a.protocolo) "
                            + "LIKE '%" + jTxtPesquisa_Multi.getText().toUpperCase() + "%' ";
                } else {
                    condicao = " ";
                }

                sql = "SELECT a.id, b.descricao as obrigacao, a.protocolo, c.razao_social "
                        + "FROM cad_prazos A "
                        + "LEFT JOIN cad_prazos_tipos B on (B.id = A.id_obrigacao) "
                        + "LEFT JOIN cad_estabelecimentos C on (C.id = A.id_estabelecimento)"
                        + condicao
                        + " ORDER BY c.razao_social, b.descricao, a.protocolo;";

                cn.conecta();
                cn.executeConsulta(sql);
                try {
                    while (cn.rs.next()) {

                        lista.addRow(new String[]{
                            cn.rs.getString("id"),
                            cn.rs.getString("obrigacao"),
                            cn.rs.getString("protocolo"),
                            cn.rs.getString("razao_social")
                        });
                    }
                } catch (SQLException ex) {

                    JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                }
                cn.desconecta();
                break;

            case 2:

                lista.addColumn("Id");
                lista.addColumn("Descrição");

                jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(60);

                if (!"".equals(jTxtPesquisa_Multi.getText())) {
                    condicao = "WHERE UPPER(descricao) "
                            + "LIKE '%" + jTxtPesquisa_Multi.getText().toUpperCase() + "%'";
                } else {
                    condicao = "";
                }

                sql = "SELECT * FROM cad_prazos_tipos "
                        + condicao
                        + " ORDER BY descricao";

                cn.conecta();
                cn.executeConsulta(sql);
                try {
                    while (cn.rs.next()) {

                        lista.addRow(new String[]{
                            cn.rs.getString("id"),
                            cn.rs.getString("descricao"),});
                    }
                } catch (SQLException ex) {

                    JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                }

                cn.desconecta();
                break;

            case 3:
                lista.addColumn("Id");
                lista.addColumn("Estabelecimento");
                lista.addColumn("Razão Social");

                jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(60);

                if (!"".equals(jTxtPesquisa_Multi.getText())) {
                    condicao = "WHERE UPPER(razao_social) "
                            + "LIKE '%" + jTxtPesquisa_Multi.getText().toUpperCase() + "%'";
                } else {
                    condicao = "";
                }

                sql = "SELECT a.id, a.razao_social, b.nome, a.inscricao_federal "
                        + "FROM cad_estabelecimentos a "
                        + "LEFT JOIN cad_empresas b on (b.id = a.id_empresa) "
                        + condicao
                        + " ORDER BY razao_social";

                cn.conecta();
                cn.executeConsulta(sql);
                try {
                    while (cn.rs.next()) {

                        lista.addRow(new String[]{
                            cn.rs.getString("id"),
                            cn.rs.getString("razao_social"),
                            cn.rs.getString("nome")
                        });
                    }
                } catch (SQLException ex) {

                    JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                }

                cn.desconecta();

            case 4:
                var_consulta = 1;
                montaLista();
                var_consulta = 4;

        }
    }
}
