/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ferramenta.SpedConfig;

/**
 *
 * @author luiz.barcellos
 */
public class ConfigSPED extends javax.swing.JInternalFrame {
    
    SpedConfig sped = new SpedConfig();
    
    private String ambiente;
    private String cod_uf;
    private String uf;
    private String servico;
    private String config;
    private String parametro;
    
    private String status = "Pesquisar";

    /**
     * Creates new form ConfigSPED
     */
    public ConfigSPED() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCbServico = new javax.swing.JComboBox<>();
        jCbAmbiente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCbConfig = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jCbEstado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTxtParam = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Conexão com o SPED");

        jLabel1.setText("Serviço");

        jCbServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CONS-CAD", "CONSULTAR", "CONSULTAR NFE DEST", "DOWNLOAD NFE", "INUTILIZAR", "STATUS" }));

        jCbAmbiente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homologação", "Produção" }));

        jLabel2.setText("Ambiente");

        jLabel3.setText("Configuração");

        jCbConfig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DefinitionsTargetNamespaceURI", "PortName", "SchemaTargetNamespaceURI", "ServiceName", "SoapActionURI", "WebServiceURL" }));

        jLabel4.setText("Estado");

        jCbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        jLabel5.setText("Parâmetro");

        jTxtParam.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtParamFocusLost(evt);
            }
        });
        jTxtParam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtParamKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCbServico, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jCbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbConfig, 0, 286, Short.MAX_VALUE))
                    .addComponent(jTxtParam))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jCbAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jCbConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtParam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        System.out.println("Parâmetro: " + sped.getParametro());
        if (null == (sped.getParametro())) {
            status = "INSERT";
        } else {
            status = "UPDATE";
        }
        
        System.out.println("Status Botão Pesquisar: " + status);
        
        sped.setAmbiente(jCbAmbiente.getSelectedItem().toString().replace("Homologação", "H").replace("Produção", "P"));
        sped.setConfig(jCbConfig.getSelectedItem().toString());
        sped.setParametro(jTxtParam.getText());
        sped.setServico(jCbServico.getSelectedItem().toString());
        sped.setUf(jCbEstado.getSelectedItem().toString());
        
        if ("Pesquisar".equals(jButton1.getText())) {
            sped.carregaConfig(null);
            
            jCbAmbiente.setSelectedItem(sped.getAmbiente().replace("H", "Homologação").replace("P", "Produção"));
            jCbConfig.setSelectedItem(sped.getConfig());
            jCbServico.setSelectedItem(sped.getServico());
            jCbEstado.setSelectedItem(sped.getUf());
            jTxtParam.setText(sped.getParametro());
            
            if (!"".equals(jTxtParam.getText())) {
                habilitarEdicao();
            } else {
                desabilitarEdicao();
            }
            
        } else {
            
            if(sped.gravaConfig(status)){
                desabilitarEdicao();
            }
            
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTxtParamFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtParamFocusLost
        if(!"".equals(jTxtParam.getText())){
            jButton1.setText("Gravar");
        } else {
            desabilitarEdicao();
        }
    }//GEN-LAST:event_jTxtParamFocusLost

    private void jTxtParamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtParamKeyReleased
        if(!"".equals(jTxtParam.getText())){
            jButton1.setText("Gravar");
        } else {
            desabilitarEdicao();
        }
    }//GEN-LAST:event_jTxtParamKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCbAmbiente;
    private javax.swing.JComboBox<String> jCbConfig;
    private javax.swing.JComboBox<String> jCbEstado;
    private javax.swing.JComboBox<String> jCbServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTxtParam;
    // End of variables declaration//GEN-END:variables

    private void habilitarEdicao() {
        jCbAmbiente.setEnabled(false);
        jCbConfig.setEnabled(false);
        jCbEstado.setEnabled(false);
        jCbServico.setEnabled(false);
        
        jButton1.setText("Gravar");
    }
    
    private void desabilitarEdicao() {
        jCbAmbiente.setEnabled(true);
        jCbConfig.setEnabled(true);
        jCbEstado.setEnabled(true);
        jCbServico.setEnabled(true);
        
        jButton1.setText("Pesquisar");
        jTxtParam.setText("");
        
        sped.setParametro(null);
    }
}
