/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luiz.barcellos
 */
public class Cons_NotaFiscal extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cons_NotaFiscal
     */
    ConexaoMySQL cn = new ConexaoMySQL();

    public Cons_NotaFiscal() {
        initComponents();

        montaListas();
        montaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCbUnidades = new javax.swing.JComboBox<>();
        jCBEmpresas = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Consulta Notas Fiscais");

        jLabel1.setText("Nota Fiscal");

        jCbUnidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCBEmpresas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente");

        jLabel3.setText("Unidade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCbUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBEmpresas, 0, 413, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel lista = (DefaultTableModel) jTable1.getModel();

        String nf = jTextField1.getText();
        String unidade = jCbUnidades.getSelectedItem().toString();
        String cliente = jCBEmpresas.getSelectedItem().toString();

        String condicao1;
        String condicao2;
        String condicao3;

        String sql;

        if (!"".equals(nf)) {
            condicao1 = " AND numero_nf = '" + nf + "' ";
        } else {
            condicao1 = " ";
        }

        if (!"TODAS".equals(unidade)) {
            condicao2 = " AND cnpj_proprio = '" + unidade + "' ";
        } else {
            condicao2 = " ";
        }

        if (!"TODAS".equals(cliente)) {
            condicao3 = " AND nome_terceiro = '" + cliente + "' ";
        } else {
            condicao3 = " ";
        }

        sql = "SELECT * FROM notas_disponiveis WHERE valor >= 0 "
                + condicao1
                + condicao2
                + condicao3
                + " ORDER BY nome_terceiro, cnpj_proprio, numero_nf";

        montaTabela();

        cn.conecta();
        cn.executeConsulta(sql);
        try {
            while (cn.rs.next()) {
                lista.addRow(new String[]{
                    cn.rs.getString("nome_terceiro"),
                    cn.rs.getString("cnpj_proprio"),
                    cn.rs.getString("numero_nf"),
                    cn.rs.getString("emissao"),
                    cn.rs.getString("quantidade3"),
                    cn.rs.getString("quantidade")
                });
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Não foi possível consultar o banco de dados.");
        }
        cn.desconecta();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBEmpresas;
    private javax.swing.JComboBox<String> jCbUnidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void montaListas() {

        jCBEmpresas.removeAllItems();
        jCbUnidades.removeAllItems();

        String sql;

        cn.conecta();
        // LISTA EMPRESAS
        sql = "select distinct a.nome_terceiro from cad_notas_fiscais a ORDER BY a.nome_terceiro";

        cn.executeConsulta(sql);
        try {
            jCBEmpresas.addItem("TODAS");
            while (cn.rs.next()) {
                jCBEmpresas.addItem(cn.rs.getString(1));
            }
            cn.rs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível montar o relatório");
        }

        //CONSULTA TODAS AS UNIDADES
        sql = "select distinct a.cnpj_proprio from cad_notas_fiscais a ORDER BY a.cnpj_proprio;";

        cn.executeConsulta(sql);

        try {
            jCbUnidades.addItem("TODAS");
            while (cn.rs.next()) {
                jCbUnidades.addItem(cn.rs.getString(1));
            }
            cn.rs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível montar o relatório");
        }
        cn.desconecta();
    }

    private void montaTabela() {
        DefaultTableModel lista = (DefaultTableModel) jTable1.getModel();

        lista.setRowCount(0);
        lista.setColumnCount(0);

        lista.addColumn("Cliente");
        lista.addColumn("Unidade");
        lista.addColumn("Documento");
        lista.addColumn("Emissao");
        lista.addColumn("Exportado");
        lista.addColumn("Disponível");

        jTable1.getColumnModel().getColumn(2).setMaxWidth(100);
        jTable1.getColumnModel().getColumn(2).setMinWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(2).setMinWidth(100);
        jTable1.getColumnModel().getColumn(3).setMaxWidth(100);
        jTable1.getColumnModel().getColumn(3).setMinWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(3).setMinWidth(100);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(100);
        jTable1.getColumnModel().getColumn(4).setMinWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(4).setMaxWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(4).setMinWidth(100);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(100);
        jTable1.getColumnModel().getColumn(5).setMinWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(5).setMaxWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(5).setMinWidth(100);
    }

}
