package View;

import View.ConexaoFB;
import View.ConexaoMySQL;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author luiz.barcellos
 */
public class IcmsRequerimento extends javax.swing.JInternalFrame {

    private int var_consulta;

    ConexaoMySQL cn = new ConexaoMySQL();

    /**
     * Creates new form IcmsRequerimento
     */
    public IcmsRequerimento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPesquisar1 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jTxtPesquisa_Multi1 = new javax.swing.JTextField();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTblConsulta_Multi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTxtId = new javax.swing.JTextField();
        jBtnPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtIdProdutor = new javax.swing.JTextField();
        jTxtNomeProdutor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtIdEstabelecimento = new javax.swing.JTextField();
        jTxtNomeEstabelecimento = new javax.swing.JTextField();
        jBtnPesquisaEstab = new javax.swing.JButton();
        jBtnPesquisaProdutor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnGravar = new javax.swing.JButton();

        jPesquisar1.setTitle("Pesquisar");
        jPesquisar1.setMinimumSize(new java.awt.Dimension(700, 400));

        jTxtPesquisa_Multi1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtPesquisa_Multi1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtPesquisa_Multi1KeyReleased(evt);
            }
        });

        jBtnConfirmar.setText("Adicionar");
        jBtnConfirmar.setEnabled(false);
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jTblConsulta_Multi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTblConsulta_Multi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblConsulta_Multi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblConsulta_MultiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTblConsulta_MultiMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(jTblConsulta_Multi);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 453, Short.MAX_VALUE)
                        .addComponent(jBtnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnConfirmar))
                    .addComponent(jTxtPesquisa_Multi1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTxtPesquisa_Multi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPesquisar1Layout = new javax.swing.GroupLayout(jPesquisar1.getContentPane());
        jPesquisar1.getContentPane().setLayout(jPesquisar1Layout);
        jPesquisar1Layout.setHorizontalGroup(
            jPesquisar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPesquisar1Layout.setVerticalGroup(
            jPesquisar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Cadastro de Processos");

        jLabel8.setText("Requerimento");

        jTxtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdFocusLost(evt);
            }
        });

        jBtnPesquisar.setText("...");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setText("Produtor");

        jTxtIdProdutor.setEnabled(false);
        jTxtIdProdutor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdProdutorFocusLost(evt);
            }
        });

        jTxtNomeProdutor.setEnabled(false);

        jLabel2.setText("Estabelecimento");

        jTxtIdEstabelecimento.setEnabled(false);
        jTxtIdEstabelecimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdEstabelecimentoFocusLost(evt);
            }
        });

        jTxtNomeEstabelecimento.setEnabled(false);

        jBtnPesquisaEstab.setText("...");
        jBtnPesquisaEstab.setEnabled(false);
        jBtnPesquisaEstab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisaEstabActionPerformed(evt);
            }
        });

        jBtnPesquisaProdutor.setText("...");
        jBtnPesquisaProdutor.setEnabled(false);
        jBtnPesquisaProdutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisaProdutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(29, 29, 29)
                        .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtIdEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNomeEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisaEstab))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtIdProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNomeProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisaProdutor)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesquisar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtIdProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesquisaProdutor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtIdEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesquisaEstab))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnEditar.setText("Editar");
        jBtnEditar.setEnabled(false);

        jBtnGravar.setText("Gravar");
        jBtnGravar.setEnabled(false);
        jBtnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnIncluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnGravar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnIncluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnEditar)
                .addGap(18, 18, 18)
                .addComponent(jBtnGravar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtIdProdutorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdProdutorFocusLost
        if (!"".equals(jTxtIdProdutor.getText())) {

            var_consulta = 22;

            IncluiPesquisa();
        }
    }//GEN-LAST:event_jTxtIdProdutorFocusLost

    private void jBtnPesquisaEstabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisaEstabActionPerformed
        var_consulta = 3;

        jPesquisar1.setVisible(true);

        montaLista();
    }//GEN-LAST:event_jBtnPesquisaEstabActionPerformed

    private void jBtnPesquisaProdutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisaProdutorActionPerformed
        var_consulta = 2;

        jPesquisar1.setVisible(true);

        montaLista();
    }//GEN-LAST:event_jBtnPesquisaProdutorActionPerformed

    private void jTxtPesquisa_Multi1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPesquisa_Multi1KeyReleased
        montaLista();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPesquisa_Multi1KeyReleased

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        IncluiPesquisa();
        jPesquisar1.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        jPesquisar1.setVisible(false);        // TODO add your handling code here:
        jPesquisar1.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTblConsulta_MultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseClicked
        jBtnConfirmar.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jTblConsulta_MultiMouseClicked

    private void jTblConsulta_MultiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTblConsulta_MultiMouseEntered

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        var_consulta = 1;

        jPesquisar1.setVisible(true);

        montaLista();
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        if ("Incluir".equals(jBtnIncluir.getText())) {
            habilitarEdicao();
            jBtnIncluir.setText("Cancelar");
            jTxtId.setText("NOVO");
        } else {
            desabilitarEdicao();
            jBtnIncluir.setText("Incluir");
            jTxtId.setText("");
        }
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jTxtIdEstabelecimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdEstabelecimentoFocusLost
        if (!"".equals(jTxtIdEstabelecimento.getText())) {

            var_consulta = 33;
            IncluiPesquisa();
        }
    }//GEN-LAST:event_jTxtIdEstabelecimentoFocusLost

    private void jBtnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGravarActionPerformed
        String sql;
        String id = jTxtId.getText();
        String id_produtor = jTxtIdProdutor.getText();
        String id_estabelecimento = jTxtIdEstabelecimento.getText();

        if ("Cancelar".equals(jBtnIncluir.getText())) {
            sql = "INSERT INTO produtor_icms (id_produtor,id_estabelecimento,"
                    + "dt_inicio_processo) "
                    + "VALUES ('" + id_produtor + "','" + id_estabelecimento + "', current_date());";
        } else {
            sql = "UPDATE produtor_icms SET id_produtor = " + id_produtor + ", "
                    + "id_estabelecimento = " + id_estabelecimento
                    + " WHERE id = " + id;
        }

        cn.conecta();
        cn.executeAtualizacao(sql);
        cn.desconecta();

        if (ConexaoMySQL.resultadoUpd < 1) {
            desabilitarEdicao();
            JOptionPane.showMessageDialog(this, "Dados gravados com sucesso.");
            jBtnIncluir.setText("Incluir");
            jTxtId.setText("");
        }

    }//GEN-LAST:event_jBtnGravarActionPerformed

    private void jTxtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdFocusLost
        if (!"".equals(jTxtId.getText())
                && !"NOVO".equals(jTxtId.getText())) {
            var_consulta = 11;
            IncluiPesquisa();
        }
    }//GEN-LAST:event_jTxtIdFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnGravar;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisaEstab;
    private javax.swing.JButton jBtnPesquisaProdutor;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JFrame jPesquisar1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTblConsulta_Multi;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtIdEstabelecimento;
    private javax.swing.JTextField jTxtIdProdutor;
    private javax.swing.JTextField jTxtNomeEstabelecimento;
    private javax.swing.JTextField jTxtNomeProdutor;
    private javax.swing.JTextField jTxtPesquisa_Multi1;
    // End of variables declaration//GEN-END:variables

    private void montaLista() {
        DefaultTableModel lista = (DefaultTableModel) jTblConsulta_Multi.getModel();
        lista.setColumnCount(0);  //limpa a tabela
        lista.setRowCount(0);     //limpa a tabela

        String sql;
        String id;

        switch (var_consulta) {
            case 1:
                lista.addColumn("Id");
                lista.addColumn("Nome");
                lista.addColumn("Processo");

                jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(60);

                jTxtPesquisa_Multi1.grabFocus();

                cn.conecta();

                if (!"".equals(jTxtPesquisa_Multi1.getText())) {
                    sql = " SELECT a.id, b.nome, c.inscri_est, a.dt_inicio_processo "
                            + "FROM produtor_icms a left join cad_pessoas b on (b.id = a.id_produtor) "
                            + "left join icms_estabelecimentos c on (c.id = a.id_estabelecimento) "
                            + "WHERE UPPER(b.nome) "
                            + "LIKE '%" + jTxtPesquisa_Multi1.getText().toUpperCase() + "%'"
                            + "OR UPPER(c.inscri_est) "
                            + "LIKE '%" + jTxtPesquisa_Multi1.getText().toUpperCase() + "%'"
                            + " ORDER BY b.nome";

                    cn.executeConsulta(sql);

                    try {
                        while (cn.rs.next()) {

                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("nome"),
                                "Processo da I.E. " + cn.rs.getString("inscri_est") + "iniciado em " + cn.rs.getString("dt_inicio_processo"),});
                        }
                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                    }

                } else { //Configuração para quando não há texto no campo pesquisa
                    sql = "SELECT a.id, b.nome, c.inscri_est, "
                            + "a.dt_inicio_processo FROM produtor_icms a "
                            + "left join cad_pessoas b on (b.id = a.id_produtor) "
                            + "left join icms_estabelecimentos c on (c.id = a.id_estabelecimento) "
                            + " ORDER BY b.nome";

                    cn.executeConsulta(sql);

                    try {
                        while (cn.rs.next()) {

                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("nome"),
                                "Processo da I.E. " + cn.rs.getString("inscri_est") + "iniciado em " + cn.rs.getString("dt_inicio_processo"),});

                        }
                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                    }

                    //Configuração dos botões, quando não há pesquisa
                }

                cn.desconecta();
                jBtnConfirmar.setEnabled(true);

                break;

            case 2:
                lista.addColumn("Id");
                lista.addColumn("Nome");
                lista.addColumn("CNPJ");
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(60);

                jTxtPesquisa_Multi1.grabFocus();

                cn.conecta();

                if (!"".equals(jTxtPesquisa_Multi1.getText())) {
                    sql = "SELECT * FROM cad_pessoas "
                            + "WHERE UPPER(nome) "
                            + "LIKE '%" + jTxtPesquisa_Multi1.getText().toUpperCase() + "%'"
                            + "OR UPPER(inscricao_federal) "
                            + "LIKE '%" + jTxtPesquisa_Multi1.getText().toUpperCase() + "%'"
                            + " ORDER BY nome";

                    cn.executeConsulta(sql);

                    try {
                        while (cn.rs.next()) {

                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("nome"),
                                cn.rs.getString("inscricao_federal")});
                        }
                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                    }

                } else { //Configuração para quando não há texto no campo pesquisa
                    sql = "SELECT * FROM cad_pessoas "
                            + " ORDER BY nome";

                    cn.executeConsulta(sql);

                    try {
                        while (cn.rs.next()) {

                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("nome"),
                                cn.rs.getString("inscricao_federal")});

                        }
                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                    }

                    //Configuração dos botões, quando não há pesquisa
                }

                cn.desconecta();
                jBtnConfirmar.setEnabled(true);
                break;

            case 3:
                id = jTxtIdProdutor.getText();

                lista.addColumn("Id");
                lista.addColumn("Descrição");
                lista.addColumn("Endereço");
                lista.addColumn("Inscrição Estadual");
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(60);

                jTxtPesquisa_Multi1.grabFocus();

                cn.conecta();

                if (!"".equals(jTxtPesquisa_Multi1.getText())) {
                    sql = "SELECT id, descricao, endereco, numero, municipio, inscri_est "
                            + "FROM icms_estabelecimentos "
                            + "WHERE id_pessoa = '" + id + "' "
                            + "AND UPPER(descricao) "
                            + "LIKE '%" + jTxtPesquisa_Multi1.getText().toUpperCase() + "%' "
                            + "OR UPPER(inscri_est) "
                            + "LIKE '%" + jTxtPesquisa_Multi1.getText().toUpperCase() + "%' "
                            + " ORDER BY descricao";

                    cn.executeConsulta(sql);

                    try {
                        while (cn.rs.next()) {

                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("descricao"),
                                cn.rs.getString("endereco") + ", " + cn.rs.getString("numero") + ", " + cn.rs.getString("municipio"),
                                cn.rs.getString("inscri_est")});
                        }
                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                    }

                } else { //Configuração para quando não há texto no campo pesquisa
                    sql = "SELECT id, descricao, endereco, numero, municipio, inscri_est "
                            + "FROM icms_estabelecimentos "
                            + "WHERE id_pessoa = '" + id + "' "
                            + " ORDER BY descricao";

                    cn.executeConsulta(sql);

                    try {
                        while (cn.rs.next()) {

                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("descricao"),
                                cn.rs.getString("endereco") + ", " + cn.rs.getString("numero") + ", " + cn.rs.getString("municipio"),
                                cn.rs.getString("inscri_est")});

                        }
                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                    }

                    //Configuração dos botões, quando não há pesquisa
                }

                cn.desconecta();
                jBtnConfirmar.setEnabled(true);

            case 33:
                break;
        }
    }

    private void IncluiPesquisa() {
        String id;
        String sql;

        int linha = jTblConsulta_Multi.getSelectedRow();

        switch (var_consulta) {
            case 1:

                jTxtId.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());

            case 11:
                jBtnEditar.setEnabled(false);
                id = jTxtId.getText();
                jTxtIdEstabelecimento.setText("");
                jTxtIdProdutor.setText("");

                cn.conecta();

                try {
                    cn.executeConsulta("SELECT * FROM produtor_icms WHERE id = " + id);
                    while (cn.rs.next()) {
                        jTxtIdEstabelecimento.setText(cn.rs.getString("id_estabelecimento"));
                        jTxtIdProdutor.setText(cn.rs.getString("id_produtor"));
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex);
                }
                cn.desconecta();

                if (!"".equals(jTxtIdProdutor.getText())) {
                    var_consulta = 22;
                    IncluiPesquisa();
                    var_consulta = 33;
                    IncluiPesquisa();

                    jBtnEditar.setEnabled(true);
                }

                break;

            case 2:
                jTxtIdProdutor.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());

            case 22:

                id = jTxtIdProdutor.getText();

                jTxtNomeProdutor.setText("");

                cn.conecta();

                try {
                    cn.executeConsulta("SELECT nome FROM cad_pessoas WHERE id = " + id);
                    while (cn.rs.next()) {
                        jTxtNomeProdutor.setText(cn.rs.getString(1));
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex);
                }
                cn.desconecta();

                break;

            case 3:
                jTxtIdEstabelecimento.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());

            case 33:
                id = jTxtIdEstabelecimento.getText();
                String id2 = jTxtIdProdutor.getText();

                jTxtNomeEstabelecimento.setText("");

                cn.conecta();
                try {
                    cn.executeConsulta("SELECT concat(endereco, ', Inscrição Estadual ', inscri_est) "
                            + "FROM icms_estabelecimentos WHERE id = " + id
                            + " AND id_pessoa = " + id2);
                    while (cn.rs.next()) {
                        jTxtNomeEstabelecimento.setText(cn.rs.getString(1));
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex);
                }

                cn.desconecta();

                break;
        }
    }

    private void habilitarEdicao() {
        jTxtId.setEnabled(false);
        jTxtIdProdutor.setEnabled(true);
        jTxtIdEstabelecimento.setEnabled(true);

        jBtnPesquisar.setEnabled(false);
        jBtnGravar.setEnabled(true);
        jBtnPesquisaProdutor.setEnabled(true);
        jBtnPesquisaEstab.setEnabled(true);
    }

    private void desabilitarEdicao() {
        jTxtId.setEnabled(true);
        jTxtIdProdutor.setEnabled(false);
        jTxtIdEstabelecimento.setEnabled(false);

        jBtnPesquisar.setEnabled(true);
        jBtnGravar.setEnabled(false);
        jBtnPesquisaProdutor.setEnabled(false);
        jBtnPesquisaEstab.setEnabled(false);
    }
}
