/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import conexoes.ConexaoMySQL;
import conexoes.ConexaoORCL;
import View.arquivo.UtilAlteraAssuntos;
import View.icms.Rel_Requerimento_ICMS;
import View.arquivo.Cad_Movimentacoes;
import View.arquivo.Cad_Departamentos;
import View.arquivo.Cad_Tipos;
import View.arquivo.Cad_Arquivo;
import View.arquivo.Cad_prazo;
import View.arquivo.Cons_Capa;
import View.arquivo.Cad_Locais;
import View.arquivo.Cad_Assuntos;
import View.arquivo.Rel_Capas;
import View.arquivo.Cad_Capas;
import View.arquivo.Cons_Arquivo;
import View.arquivo.Rel_Etiquetas;
import View.icms.BaixaCreditos;
import View.icms.Icms_sc_nf_saidas;
import View.icms.icms_agencias;
import View.icms.IcmsProcuracao;
import View.icms.IcmsAceiteCredito;
import View.icms.IcmsRequerimento;
import View.icms.RelAceiteIcms;
import java.awt.Dimension;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author luiz.barcellos
 */
public final class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    ConexaoMySQL cn = new ConexaoMySQL();
    
    public static int usuariosys;
    
    public TelaInicial() {
        initComponents();
        setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        //Contagem();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //CAPTURA DADOS DE OUTRAS TELAS E MOSTRA NA TELA INICIAL
    public static void recebendo(String usuariolog, int id) {
        jTxtUsuario.setText(id + " - " + usuariolog);
        usuariosys = id;

        //controlaAcesso();
    }

    //BUSCA DADOS DA CONEXÃO NO ARQUIVO TEXTO
    //CONTA QUANTOS LANÇAMENTOS JÁ FORAM REALIZADOS
    public void Contagem() {
        String sql = "SELECT  'MEMORANDOS' AS TIPO, "
                + "count(a.id) as QUANTIDADE "
                + "from cad_memorandos a "
                + "UNION ALL "
                + "SELECT  'PROCESSADAS' AS TIPO, "
                + "count(a.id) as QUANTIDADE "
                + "from cad_memorandos_detalhe a "
                + "UNION ALL "
                + "SELECT  'CADASTRADAS' AS TIPO, "
                + "count(a.id) as QUANTIDADE "
                + "from cad_notas_fiscais a ";
        
        cn.conecta();
        cn.executeConsulta(sql);
        
        try {
            while (cn.rs.next()) {
                if (cn.rs.getString("TIPO").equals("MEMORANDOS")) {
                    jTxtContMem.setText(cn.rs.getString("QUANTIDADE"));
                } else if (cn.rs.getString("TIPO").equals("PROCESSADAS")) {
                    jTxtContNfP.setText(cn.rs.getString("QUANTIDADE"));
                } else if (cn.rs.getString("TIPO").equals("CADASTRADAS")) {
                    jTxtContNfC.setText(cn.rs.getString("QUANTIDADE"));
                    
                }
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        cn.desconecta();
        
    }
    
    public void ContagemArquivo() {
        String sql = "select 'CAPAS' as tipo, "
                + "count(id) as qtd "
                + "from cad_arquivo_capas "
                + "union all "
                + "select 'ETIQUETAS' as tipo, "
                + "count(id) as qtd "
                + "from cad_arquivo_pastas;";
        
        cn.conecta();
        cn.executeConsulta(sql);
        
        try {
            while (cn.rs.next()) {
                if (cn.rs.getString("TIPO").equals("CAPAS")) {
                    jTxtContCapas.setText(cn.rs.getString("qtd"));
                } else if (cn.rs.getString("TIPO").equals("ETIQUETAS")) {
                    jTxtContEtiquetas.setText(cn.rs.getString("qtd"));
                    
                }
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        cn.desconecta();
        
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrmresumoMemorandos = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jTxtContNfC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtContNfP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtContMem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBtnAtualizarResumo = new javax.swing.JButton();
        jBtnCancelarResumo = new javax.swing.JButton();
        jFrmresumoArquivo = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jTxtContEtiquetas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtContCapas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jBtnAtualizarArquivo = new javax.swing.JButton();
        jBtnCancelarArquivo = new javax.swing.JButton();
        jDPTelaPrincipal = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jTxtUsuario = new javax.swing.JTextField();
        jTxtVersao = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnArquivo = new javax.swing.JMenu();
        jMnEstabelecimentos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMnConfiguracao = new javax.swing.JMenuItem();
        jMnConfiguracao2 = new javax.swing.JMenuItem();
        jMnConfiguracao3 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMniCadastro = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMnConfiguracao1 = new javax.swing.JMenuItem();
        jMnNotas = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMnCadastros = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMniSair = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMniPessoas = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMniMemorandos = new javax.swing.JMenuItem();
        jMnuArquivoMorto = new javax.swing.JMenu();
        jMniTipos = new javax.swing.JMenuItem();
        jMniAssuntos = new javax.swing.JMenuItem();
        jMniDepartamentos = new javax.swing.JMenuItem();
        jMniLocais = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMniCapas = new javax.swing.JMenuItem();
        jMniArquivo = new javax.swing.JMenuItem();
        jMniMovimento = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMniExtracao = new javax.swing.JMenuItem();
        jMniDevolucao = new javax.swing.JMenuItem();
        jMniDescarte = new javax.swing.JMenuItem();
        jMnuSeguros = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMnIcms = new javax.swing.JMenu();
        jMenuItem25 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMnConsultas = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMniRelNF = new javax.swing.JMenuItem();
        jMniRelPaises = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMniRelCapas = new javax.swing.JMenuItem();
        jMniRelEtiquetas = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMnUtilitários = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMnTabelas = new javax.swing.JMenu();
        jMniLimpaPessoas = new javax.swing.JMenuItem();
        jMniLimpaMemorandos = new javax.swing.JMenuItem();
        jMniLimpraNFMem = new javax.swing.JMenuItem();
        jMniLimpraNfProp = new javax.swing.JMenuItem();
        jMnUtilAssuntos = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMnTransporte = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMnSobre = new javax.swing.JMenu();

        jFrmresumoMemorandos.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrmresumoMemorandos.setTitle("Resumo Memorandos");
        jFrmresumoMemorandos.setMinimumSize(new java.awt.Dimension(300, 304));
        jFrmresumoMemorandos.setResizable(false);

        jTxtContNfC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxtContNfC.setEnabled(false);

        jLabel3.setText("Notas Fiscais Importadas");

        jTxtContNfP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxtContNfP.setEnabled(false);

        jLabel2.setText("Notas Fiscais Apropriadas");

        jTxtContMem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxtContMem.setEnabled(false);

        jLabel1.setText("Memorandos Cadastrados");

        jBtnAtualizarResumo.setText("Atualizar");
        jBtnAtualizarResumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAtualizarResumoActionPerformed(evt);
            }
        });

        jBtnCancelarResumo.setText("Cancelar");
        jBtnCancelarResumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarResumoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtContMem)
                    .addComponent(jTxtContNfP)
                    .addComponent(jTxtContNfC)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnAtualizarResumo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(jBtnCancelarResumo)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtContMem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtContNfP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtContNfC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAtualizarResumo)
                    .addComponent(jBtnCancelarResumo))
                .addContainerGap())
        );

        javax.swing.GroupLayout jFrmresumoMemorandosLayout = new javax.swing.GroupLayout(jFrmresumoMemorandos.getContentPane());
        jFrmresumoMemorandos.getContentPane().setLayout(jFrmresumoMemorandosLayout);
        jFrmresumoMemorandosLayout.setHorizontalGroup(
            jFrmresumoMemorandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrmresumoMemorandosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrmresumoMemorandosLayout.setVerticalGroup(
            jFrmresumoMemorandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrmresumoMemorandosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jFrmresumoArquivo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrmresumoArquivo.setTitle("Resumo Memorandos");
        jFrmresumoArquivo.setMinimumSize(new java.awt.Dimension(300, 304));
        jFrmresumoArquivo.setResizable(false);

        jPanel2.setMaximumSize(new java.awt.Dimension(300, 192));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 192));

        jTxtContEtiquetas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxtContEtiquetas.setEnabled(false);

        jLabel5.setText("Etiquetas Cadastradas");

        jTxtContCapas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxtContCapas.setEnabled(false);

        jLabel6.setText("Capas Cadastradas");

        jBtnAtualizarArquivo.setText("Atualizar");
        jBtnAtualizarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAtualizarArquivoActionPerformed(evt);
            }
        });

        jBtnCancelarArquivo.setText("Cancelar");
        jBtnCancelarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarArquivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtContCapas)
                    .addComponent(jTxtContEtiquetas)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBtnAtualizarArquivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(jBtnCancelarArquivo)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtContCapas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtContEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAtualizarArquivo)
                    .addComponent(jBtnCancelarArquivo))
                .addContainerGap())
        );

        javax.swing.GroupLayout jFrmresumoArquivoLayout = new javax.swing.GroupLayout(jFrmresumoArquivo.getContentPane());
        jFrmresumoArquivo.getContentPane().setLayout(jFrmresumoArquivoLayout);
        jFrmresumoArquivoLayout.setHorizontalGroup(
            jFrmresumoArquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrmresumoArquivoLayout.setVerticalGroup(
            jFrmresumoArquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sisteminha :p");
        setBackground(new java.awt.Color(102, 102, 102));
        setLocationByPlatform(true);

        javax.swing.GroupLayout jDPTelaPrincipalLayout = new javax.swing.GroupLayout(jDPTelaPrincipal);
        jDPTelaPrincipal.setLayout(jDPTelaPrincipalLayout);
        jDPTelaPrincipalLayout.setHorizontalGroup(
            jDPTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1351, Short.MAX_VALUE)
        );
        jDPTelaPrincipalLayout.setVerticalGroup(
            jDPTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        jTxtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtUsuario.setEnabled(false);

        jTxtVersao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtVersao.setText("Versão: 1.1");
        jTxtVersao.setEnabled(false);
        jTxtVersao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtVersaoActionPerformed(evt);
            }
        });

        jButton1.setText("Atualizar Permissões");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Trocar Usuário");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(574, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVersao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 0, 51));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMnArquivo.setMnemonic('A');
        jMnArquivo.setText("Controle");
        jMnArquivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMnEstabelecimentos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnEstabelecimentos.setText("Estabelecimentos");
        jMnEstabelecimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnEstabelecimentosActionPerformed(evt);
            }
        });
        jMnArquivo.add(jMnEstabelecimentos);

        jMenu4.setText("Configuração");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMnConfiguracao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnConfiguracao.setText("Conexão");
        jMnConfiguracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnConfiguracaoActionPerformed(evt);
            }
        });
        jMenu4.add(jMnConfiguracao);

        jMnConfiguracao2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnConfiguracao2.setText("Sped");
        jMnConfiguracao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnConfiguracao2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMnConfiguracao2);

        jMnConfiguracao3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnConfiguracao3.setText("Parâmetros");
        jMnConfiguracao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnConfiguracao3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMnConfiguracao3);

        jMnArquivo.add(jMenu4);

        jMenu7.setText("Usuários");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMniCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniCadastro.setText("Cadastro");
        jMniCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniCadastroActionPerformed(evt);
            }
        });
        jMenu7.add(jMniCadastro);

        jMenuItem26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem26.setText("Alterar Senha");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem26);

        jMnConfiguracao1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnConfiguracao1.setText("Trocar Usuário");
        jMnConfiguracao1.setEnabled(false);
        jMnConfiguracao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnConfiguracao1ActionPerformed(evt);
            }
        });
        jMenu7.add(jMnConfiguracao1);

        jMnArquivo.add(jMenu7);

        jMnNotas.setText("Importar Notas");
        jMnNotas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem6.setText("Do Arquivo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMnNotas.add(jMenuItem6);

        jMenuItem17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem17.setText("Automático");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMnNotas.add(jMenuItem17);

        jMnArquivo.add(jMnNotas);

        jMnCadastros.setText("Importar Cadastros");
        jMnCadastros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem23.setText("Pessoas");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMnCadastros.add(jMenuItem23);

        jMenuItem24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem24.setText("Estabelecimentos");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMnCadastros.add(jMenuItem24);

        jMnArquivo.add(jMnCadastros);
        jMnArquivo.add(jSeparator1);

        jMniSair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniSair.setMnemonic('S');
        jMniSair.setText("Sair");
        jMniSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniSairActionPerformed(evt);
            }
        });
        jMnArquivo.add(jMniSair);

        jMenuBar1.add(jMnArquivo);

        jMenu1.setMnemonic('M');
        jMenu1.setText("Manutenção");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMniPessoas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniPessoas.setText("Cadastro de Terceiros");
        jMniPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniPessoasActionPerformed(evt);
            }
        });
        jMenu1.add(jMniPessoas);
        jMenu1.add(jSeparator4);

        jMniMemorandos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniMemorandos.setMnemonic('C');
        jMniMemorandos.setText("Memorandos");
        jMniMemorandos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniMemorandosActionPerformed(evt);
            }
        });
        jMenu1.add(jMniMemorandos);

        jMnuArquivoMorto.setText("Arquivo");
        jMnuArquivoMorto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMniTipos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniTipos.setText("Tipos");
        jMniTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniTiposActionPerformed(evt);
            }
        });
        jMnuArquivoMorto.add(jMniTipos);

        jMniAssuntos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniAssuntos.setText("Assuntos");
        jMniAssuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniAssuntosActionPerformed(evt);
            }
        });
        jMnuArquivoMorto.add(jMniAssuntos);

        jMniDepartamentos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniDepartamentos.setText("Departamentos");
        jMniDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniDepartamentosActionPerformed(evt);
            }
        });
        jMnuArquivoMorto.add(jMniDepartamentos);

        jMniLocais.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniLocais.setText("Locais");
        jMniLocais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniLocaisActionPerformed(evt);
            }
        });
        jMnuArquivoMorto.add(jMniLocais);
        jMnuArquivoMorto.add(jSeparator6);

        jMniCapas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniCapas.setText("Capas");
        jMniCapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniCapasActionPerformed(evt);
            }
        });
        jMnuArquivoMorto.add(jMniCapas);

        jMniArquivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniArquivo.setText("Arquivamento");
        jMniArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniArquivoActionPerformed(evt);
            }
        });
        jMnuArquivoMorto.add(jMniArquivo);

        jMniMovimento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMniMovimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniMovimento.setText("Movimentação");
        jMniMovimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniMovimentoActionPerformed(evt);
            }
        });
        jMnuArquivoMorto.add(jMniMovimento);
        jMnuArquivoMorto.add(jSeparator5);

        jMniExtracao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniExtracao.setText("Extração");
        jMniExtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniExtracaoActionPerformed(evt);
            }
        });
        jMnuArquivoMorto.add(jMniExtracao);

        jMniDevolucao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniDevolucao.setText("Devolução");
        jMniDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniDevolucaoActionPerformed(evt);
            }
        });
        jMnuArquivoMorto.add(jMniDevolucao);

        jMniDescarte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniDescarte.setText("Descarte");
        jMniDescarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniDescarteActionPerformed(evt);
            }
        });
        jMnuArquivoMorto.add(jMniDescarte);

        jMenu1.add(jMnuArquivoMorto);

        jMnuSeguros.setText("Seguros");
        jMnuSeguros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem1.setText("Bens");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMnuSeguros.add(jMenuItem1);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem8.setText("Tipos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMnuSeguros.add(jMenuItem8);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem2.setText("Coberturas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMnuSeguros.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem3.setText("Apólices");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMnuSeguros.add(jMenuItem3);

        jMenu1.add(jMnuSeguros);

        jMenu2.setText("Controle de Prazos");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem9.setText("Tipos de obrigações");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem10.setText("Solicitação / Renovação");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenu1.add(jMenu2);
        jMenu1.add(jSeparator7);

        jMnIcms.setText("Processo ICMS / SC");
        jMnIcms.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem25.setText("Agências da Receita Estadual");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMnIcms.add(jMenuItem25);
        jMnIcms.add(jSeparator10);

        jMenuItem19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem19.setText("Requerimento");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMnIcms.add(jMenuItem19);

        jMenuItem21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem21.setText("Relação de Documentos");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMnIcms.add(jMenuItem21);

        jMenuItem28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem28.setText("Procuração");
        jMenuItem28.setEnabled(false);
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMnIcms.add(jMenuItem28);

        jMenuItem20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem20.setText("Aceite do Crédito");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMnIcms.add(jMenuItem20);

        jMenuItem30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem30.setText("Recebimento do Crédito");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMnIcms.add(jMenuItem30);

        jMenu1.add(jMnIcms);

        jMenuBar1.add(jMenu1);

        jMnConsultas.setText("Consultas");
        jMnConsultas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem4.setText("Memorandos");
        jMnConsultas.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem5.setText("Notas Fiscais Próprias");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMnConsultas.add(jMenuItem5);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem7.setText("Resumo Memorandos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMnConsultas.add(jMenuItem7);
        jMnConsultas.add(jSeparator3);

        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem14.setText("Pesquisa Arquivo");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMnConsultas.add(jMenuItem14);

        jMenuItem22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem22.setText("Pesquisa Capa");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMnConsultas.add(jMenuItem22);

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem12.setText("Resumo Arquivo");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMnConsultas.add(jMenuItem12);

        jMenuBar1.add(jMnConsultas);

        jMenu3.setText("Relatórios");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMniRelNF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniRelNF.setText("Notas Fiscais Pendentes");
        jMniRelNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniRelNFActionPerformed(evt);
            }
        });
        jMenu3.add(jMniRelNF);

        jMniRelPaises.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniRelPaises.setText("Países Importadores");
        jMenu3.add(jMniRelPaises);
        jMenu3.add(jSeparator2);

        jMniRelCapas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniRelCapas.setText("Emissão de Capas");
        jMniRelCapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniRelCapasActionPerformed(evt);
            }
        });
        jMenu3.add(jMniRelCapas);

        jMniRelEtiquetas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniRelEtiquetas.setText("Emissão de Etiquetas");
        jMniRelEtiquetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniRelEtiquetasActionPerformed(evt);
            }
        });
        jMenu3.add(jMniRelEtiquetas);

        jMenuItem15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem15.setText("Arquivo Emprestado");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem15);
        jMenu3.add(jSeparator9);

        jMenuItem27.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItem27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem27.setText("Requerimentos ICMS");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem27);

        jMenuItem29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem29.setText("Aceite ICMS");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem29);

        jMenuBar1.add(jMenu3);

        jMnUtilitários.setText("Utilitários");
        jMnUtilitários.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem16.setText("Backup");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMnUtilitários.add(jMenuItem16);

        jMnTabelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tabelas.png"))); // NOI18N
        jMnTabelas.setText("Tabelas");
        jMnTabelas.setEnabled(false);
        jMnTabelas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMniLimpaPessoas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniLimpaPessoas.setText("Limpar Tabela Pessoas");
        jMniLimpaPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniLimpaPessoasActionPerformed(evt);
            }
        });
        jMnTabelas.add(jMniLimpaPessoas);

        jMniLimpaMemorandos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniLimpaMemorandos.setText("Limpar Tabela Memorandos");
        jMniLimpaMemorandos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniLimpaMemorandosActionPerformed(evt);
            }
        });
        jMnTabelas.add(jMniLimpaMemorandos);

        jMniLimpraNFMem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniLimpraNFMem.setText("Limpar Tabela Notas Fiscais Memorando");
        jMniLimpraNFMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniLimpraNFMemActionPerformed(evt);
            }
        });
        jMnTabelas.add(jMniLimpraNFMem);

        jMniLimpraNfProp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMniLimpraNfProp.setText("Limpar Tabela Notas Próprias");
        jMniLimpraNfProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniLimpraNfPropActionPerformed(evt);
            }
        });
        jMnTabelas.add(jMniLimpraNfProp);

        jMnUtilitários.add(jMnTabelas);

        jMnUtilAssuntos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnUtilAssuntos.setText("Altera Assuntos");
        jMnUtilAssuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnUtilAssuntosActionPerformed(evt);
            }
        });
        jMnUtilitários.add(jMnUtilAssuntos);
        jMnUtilitários.add(jSeparator8);

        jMnTransporte.setText("Transporte");
        jMnTransporte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem18.setText("Emissão de RPA");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMnTransporte.add(jMenuItem18);

        jMnUtilitários.add(jMnTransporte);

        jMenuBar1.add(jMnUtilitários);

        jMnSobre.setText("Sobre");
        jMnSobre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMnSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPTelaPrincipal)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDPTelaPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniSairActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMniSairActionPerformed

    private void jMniLimpaMemorandosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniLimpaMemorandosActionPerformed
        cn.conecta();
        String sql = " TRUNCATE cad_memorandos ";
        cn.executeAtualizacao(sql);
        cn.desconecta();// TODO add your handling code here:
    }//GEN-LAST:event_jMniLimpaMemorandosActionPerformed

    private void jMniLimpaPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniLimpaPessoasActionPerformed
        cn.conecta();
        String sql = " TRUNCATE cad_pessoas ";
        cn.executeAtualizacao(sql);
        cn.desconecta();    // TODO add your handling code here:
    }//GEN-LAST:event_jMniLimpaPessoasActionPerformed

    private void jMniLimpraNFMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniLimpraNFMemActionPerformed
        cn.conecta();
        String sql = " TRUNCATE cad_memorandos_detalhe ";
        cn.executeAtualizacao(sql);
        cn.desconecta();    // TODO add your handling code here:
    }//GEN-LAST:event_jMniLimpraNFMemActionPerformed

    private void jMniMemorandosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniMemorandosActionPerformed
        try {
            Cad_Memorandos mem = new Cad_Memorandos();
            mem.setVisible(true);
            //mem.setPosicao();
            jDPTelaPrincipal.add(mem);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jMniMemorandosActionPerformed

    private void jMniPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniPessoasActionPerformed
        try {
            Cad_Pessoas pes = new Cad_Pessoas();
            pes.setVisible(true);
            //pes.setPosicao();
            jDPTelaPrincipal.add(pes);// TODO add your handling code here:
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jMniPessoasActionPerformed

    private void jMniLimpraNfPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniLimpraNfPropActionPerformed
        ConexaoMySQL cn = new ConexaoMySQL();
        cn.conecta();
        String sql = " TRUNCATE cad_notas_fiscais ";
        cn.executeAtualizacao(sql);
        cn.desconecta();        // TODO add your handling code here:
    }//GEN-LAST:event_jMniLimpraNfPropActionPerformed

    private void jBtnAtualizarResumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAtualizarResumoActionPerformed
        
        Contagem();        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAtualizarResumoActionPerformed

    private void jMniArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniArquivoActionPerformed
        try {
            Cad_Arquivo arq = new Cad_Arquivo();
            arq.setVisible(true);
            jDPTelaPrincipal.add(arq);
            arq.setPosicao();
            arq.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Este PC não estabeleceu conexão com o Banco de Dados. " + e);
        }
    }//GEN-LAST:event_jMniArquivoActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jFrmresumoMemorandos.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jBtnCancelarResumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarResumoActionPerformed
        jFrmresumoMemorandos.dispose();
    }//GEN-LAST:event_jBtnCancelarResumoActionPerformed

    private void jMniLocaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniLocaisActionPerformed
        try {
            Cad_Locais lc = new Cad_Locais();
            lc.setVisible(true);
            jDPTelaPrincipal.add(lc);
            lc.setPosicao();
            lc.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Locais. " + e);
        }
    }//GEN-LAST:event_jMniLocaisActionPerformed

    private void jMniMovimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniMovimentoActionPerformed
        try {
            Cad_Movimentacoes mov = new Cad_Movimentacoes();
            mov.setVisible(true);
            jDPTelaPrincipal.add(mov);
            mov.setPosicao();
            mov.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Locais. " + e);
        }
    }//GEN-LAST:event_jMniMovimentoActionPerformed

    private void jMniTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniTiposActionPerformed
        try {
            Cad_Tipos tp = new Cad_Tipos();
            tp.setVisible(true);
            jDPTelaPrincipal.add(tp);
            tp.setPosicao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Locais. " + e);
        }
    }//GEN-LAST:event_jMniTiposActionPerformed

    private void jMniExtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniExtracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMniExtracaoActionPerformed

    private void jMniDescarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniDescarteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMniDescarteActionPerformed

    private void jMniRelCapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniRelCapasActionPerformed
        try {
            Rel_Capas cps = new Rel_Capas();
            cps.setVisible(true);
            jDPTelaPrincipal.add(cps);
            cps.setPosicao();
            cps.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Assuntos. " + e);
        }
    }//GEN-LAST:event_jMniRelCapasActionPerformed

    private void jMniRelEtiquetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniRelEtiquetasActionPerformed
        try {
            Rel_Etiquetas etq = new Rel_Etiquetas();
            etq.setVisible(true);
            jDPTelaPrincipal.add(etq);
            etq.setPosicao();
            etq.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Assuntos. " + e);
        }
    }//GEN-LAST:event_jMniRelEtiquetasActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        try {
            Cons_Arquivo carq = new Cons_Arquivo();
            carq.setVisible(true);
            jDPTelaPrincipal.add(carq);
            carq.setPosicao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Consulta. " + e);
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMniAssuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniAssuntosActionPerformed
        try {
            Cad_Assuntos as = new Cad_Assuntos();
            as.setVisible(true);
            jDPTelaPrincipal.add(as);
            as.setPosicao();
            as.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Assuntos. " + e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jMniAssuntosActionPerformed

    private void jMniCapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniCapasActionPerformed
        try {
            Cad_Capas cap = new Cad_Capas();
            cap.setVisible(true);
            jDPTelaPrincipal.add(cap);
            cap.setPosicao();
            cap.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Assuntos. " + e);
        }
    }//GEN-LAST:event_jMniCapasActionPerformed

    private void jMniDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniDevolucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMniDevolucaoActionPerformed

    private void jTxtVersaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtVersaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtVersaoActionPerformed

    private void jMniDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniDepartamentosActionPerformed
        try {
            Cad_Departamentos dep = new Cad_Departamentos();
            dep.setVisible(true);
            jDPTelaPrincipal.add(dep);
            dep.setPosicao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Empresas. " + e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jMniDepartamentosActionPerformed
    

    private void jMniRelNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniRelNFActionPerformed
        try {
            Rel_Memorandos nfp = new Rel_Memorandos();
            nfp.setVisible(true);
            jDPTelaPrincipal.add(nfp);
            nfp.setPosicao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Notas Pendentes. " + e);
        }
    }//GEN-LAST:event_jMniRelNFActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        try {
            Importar_Notas imp = new Importar_Notas();
            imp.setVisible(true);
            jDPTelaPrincipal.add(imp);
            imp.setPosicao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Notas Pendentes. " + e);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMnEstabelecimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnEstabelecimentosActionPerformed
        try {
            Cad_Estabelecimentos cest = new Cad_Estabelecimentos();
            cest.setVisible(true);
            jDPTelaPrincipal.add(cest);
            cest.setPosicao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Estabelecimentos. " + e);
        }
    }//GEN-LAST:event_jMnEstabelecimentosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            cad_bens bens = new cad_bens();
            bens.setVisible(true);
            jDPTelaPrincipal.add(bens);
            bens.setPosicao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Bens. " + e);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        try {
            Cad_Seguros_Tipos tipos = new Cad_Seguros_Tipos();
            tipos.setVisible(true);
            jDPTelaPrincipal.add(tipos);
            tipos.setPosicao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Tipos de Seguros. " + e);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            Cad_Seguros_Coberturas cob = new Cad_Seguros_Coberturas();
            cob.setVisible(true);
            jDPTelaPrincipal.add(cob);
            cob.setPosicao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Tipos de Seguros. " + e);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            Cad_Seguros_Apolice apo = new Cad_Seguros_Apolice();
            apo.setVisible(true);
            jDPTelaPrincipal.add(apo);
            apo.setPosicao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Tipos de Seguros. " + e);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jBtnAtualizarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAtualizarArquivoActionPerformed
        
        ContagemArquivo();

// TODO add your handling code here:
    }//GEN-LAST:event_jBtnAtualizarArquivoActionPerformed

    private void jBtnCancelarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarArquivoActionPerformed
        jFrmresumoArquivo.dispose();
    }//GEN-LAST:event_jBtnCancelarArquivoActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        jFrmresumoArquivo.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        try {
            Backup bkp = new Backup();
            bkp.setVisible(true);
            jDPTelaPrincipal.add(bkp);
            //bkp.setPosicao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Backup. " + e);
        }

        /*
        cn.conecta();
        
        try {
            File file = new File("Backup");
            file.mkdir();
            String nomeBkp = "sistemaBKP.sql";
            String dump = "cmd.exe /c mysqldump --user=root --password=root backup > Backup/" + nomeBkp;
            Runtime bkp = Runtime.getRuntime();
            bkp.exec(dump);
            JOptionPane.showMessageDialog(rootPane, "Backup realizado com sucesso!");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "erro" + ex.getMessage());
        }
        cn.desconecta();
        
        DateTime cal = new DateTime();
	  int dia = cal.getDayOfMonth();
	  int mes = cal.getMonthOfYear();
	  int ano = cal.getYear();
	  String snh = ""; //props.getSenha_bd();
	  String banco ="studio"; // props.getNm_banco();
	  File diretorio = new File("D:/SDO-Backup");
	  File arquivo = new File("D:/SDO-Backup/bkp_"+banco+"_"+ano+"_"+mes+"_"+dia+".sql");
	  Boolean snbkp = true;
	  // Cria diretório
	  if(!diretorio.isDirectory()) new File("D:/SDO-Backup").mkdir();
	  // Cria Arquivo de Backup
	  try {
	  	  if (arquivo.isFile()){ 
			  if(JOptionPane.showConfirmDialog(null,"Ja foi criado backup hoje, deseja substituir ?","Backup ja existe",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION)
			  { 
				  arquivo.delete();
				  snbkp = true;
			  }
			  else
			  {
				  snbkp = false;
			  } 
		  }
		  if(snbkp==true)
		  { 
/*
			  Process proc =  
					  Runtime.getRuntime().exec("cmd /c mysqldump -uroot -p"+snh+" -h "+ip+" "+banco+" --result-file=D:/SDO-Backup/bkp_"+banco+"_"+ano+
		  "_"+mes+"_"+dia+".sql"); proc.waitFor();
         */
 /*			  String comando = "C:\\Program Files (x86)\\MySQL\\MySQL Server 5.1\\bin\\mysqldump";
				ProcessBuilder pb = new ProcessBuilder(comando, "--user=root",
						"--password="+snh, banco, "--result-file=D:\\SDO-Backup\\bkp_" +banco+"_"+ano+
						  "_"+mes+"_"+dia+".sql");
				pb.start();
			  int res = 0;//proc.exitValue();
		  if (res == 0)
			  JOptionPane.showMessageDialog(null,"Backup criado com Sucesso !");
		  else 	{
			  JOptionPane.showMessageDialog(null,"Falha ao criar Backup. \n Verifique as configurações ou entre em contato com o suporte !",
					  "Erro ao criar backup", JOptionPane.ERROR_MESSAGE);
		  	  } 
		  }
	  }
	  catch (IOException ex) {
		  ex.printStackTrace();
		  System.out.println(ex); 
		  JOptionPane.showMessageDialog(null,"Erro na criação do Backup !");
	  } catch(Exception err){
		  System.out.println(err);
		  JOptionPane.showMessageDialog(null,"Erro na criação do Backup !");
	  }
         */
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        try {
            Importar_Automatico iaut = new Importar_Automatico();
            iaut.setVisible(true);
            jDPTelaPrincipal.add(iaut);
            //iaut.setPosicao();
            iaut.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Backup. " + e);
        }
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMnUtilAssuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnUtilAssuntosActionPerformed
        try {
            UtilAlteraAssuntos x = new UtilAlteraAssuntos();
            x.setVisible(true);
            jDPTelaPrincipal.add(x);
            //iaut.setPosicao();
            x.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Manutenção. " + e);
        }
    }//GEN-LAST:event_jMnUtilAssuntosActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        try {
            IcmsRequerimento x = new IcmsRequerimento();
            x.setVisible(true);
            jDPTelaPrincipal.add(x);
            //iaut.setPosicao();
            x.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Manutenção. " + e);
        }
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        abreTelaInterna(new IcmsAceiteCredito());
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        try {
            Icms_sc_nf_saidas x = new Icms_sc_nf_saidas();
            x.setVisible(true);
            jDPTelaPrincipal.add(x);
            //iaut.setPosicao();
            x.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Manutenção. " + e);
        }
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        try {
            Cons_Capa x = new Cons_Capa();
            x.setVisible(true);
            jDPTelaPrincipal.add(x);
            //iaut.setPosicao();
            x.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Manutenção. " + e);
        }
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        try {
            ImportarPessoas x = new ImportarPessoas();
            x.setVisible(true);
            jDPTelaPrincipal.add(x);
            //iaut.setPosicao();
            x.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Manutenção. " + e);
        }
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        try {
            ImportarEstab x = new ImportarEstab();
            x.setVisible(true);
            jDPTelaPrincipal.add(x);
            //iaut.setPosicao();
            x.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Manutenção. " + e);
        }
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMniCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniCadastroActionPerformed
        try {
            cad_usuarios x = new cad_usuarios();
            x.setVisible(true);
            jDPTelaPrincipal.add(x);
            //iaut.setPosicao();
            x.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de Usuários. " + e);
        }
    }//GEN-LAST:event_jMniCadastroActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        try {
            cad_senha x = new cad_senha();
            x.setVisible(true);
            jDPTelaPrincipal.add(x);
            //iaut.setPosicao();
            x.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de senhas. " + e);
        }
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controlaAcesso();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Troca_usuario x = new Troca_usuario();
            x.setVisible(true);
            jDPTelaPrincipal.add(x);
            //iaut.setPosicao();
            x.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de senhas. " + e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        ConexaoORCL cno = new ConexaoORCL();
        
        cno.conecta();
        cno.desconecta();
        

    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMnConfiguracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnConfiguracaoActionPerformed
        try {
            ConfConexao x = new ConfConexao();
            x.setVisible(true);
            jDPTelaPrincipal.add(x);
            //iaut.setPosicao();
            x.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de configurações. " + e);
        }
    }//GEN-LAST:event_jMnConfiguracaoActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        try {
            Cad_Prazos_Tipos x = new Cad_Prazos_Tipos();
            x.setVisible(true);
            jDPTelaPrincipal.add(x);
            //iaut.setPosicao();
            x.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de configurações. " + e);
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMnConfiguracao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnConfiguracao1ActionPerformed
        try {
            Troca_usuario x = new Troca_usuario();
            x.setVisible(true);
            jDPTelaPrincipal.add(x);
            //iaut.setPosicao();
            x.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de configurações. " + e);
        }
    }//GEN-LAST:event_jMnConfiguracao1ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        try {
            Cad_prazo x = new Cad_prazo();
            x.setVisible(true);
            jDPTelaPrincipal.add(x);
            //iaut.setPosicao();
            x.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de configurações. " + e);
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            Cons_NotaFiscal x = new Cons_NotaFiscal();
            x.setVisible(true);
            jDPTelaPrincipal.add(x);
            //iaut.setPosicao();
            x.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de configurações. " + e);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        try {
            icms_agencias x = new icms_agencias();
            x.setVisible(true);
            jDPTelaPrincipal.add(x);
            //iaut.setPosicao();
            x.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de configurações. " + e);
        }
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        try {
            Rel_Requerimento_ICMS x = new Rel_Requerimento_ICMS();
            x.setVisible(true);
            jDPTelaPrincipal.add(x);
            //iaut.setPosicao();
            x.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de configurações. " + e);
        }
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMnConfiguracao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnConfiguracao2ActionPerformed
        try {
            ConfigSPED x = new ConfigSPED();
            x.setVisible(true);
            jDPTelaPrincipal.add(x);
            //iaut.setPosicao();
            x.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela de configurações. " + e);
        }
    }//GEN-LAST:event_jMnConfiguracao2ActionPerformed

    private void jMnConfiguracao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnConfiguracao3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnConfiguracao3ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        abreTelaInterna(new IcmsProcuracao());
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        abreTelaInterna(new RelAceiteIcms());        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        abreTelaInterna(new BaixaCreditos());
    }//GEN-LAST:event_jMenuItem30ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAtualizarArquivo;
    private javax.swing.JButton jBtnAtualizarResumo;
    private javax.swing.JButton jBtnCancelarArquivo;
    private javax.swing.JButton jBtnCancelarResumo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JDesktopPane jDPTelaPrincipal;
    private javax.swing.JFrame jFrmresumoArquivo;
    private javax.swing.JFrame jFrmresumoMemorandos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jMnArquivo;
    private javax.swing.JMenu jMnCadastros;
    private javax.swing.JMenuItem jMnConfiguracao;
    private javax.swing.JMenuItem jMnConfiguracao1;
    private javax.swing.JMenuItem jMnConfiguracao2;
    private javax.swing.JMenuItem jMnConfiguracao3;
    private javax.swing.JMenu jMnConsultas;
    private javax.swing.JMenuItem jMnEstabelecimentos;
    private javax.swing.JMenu jMnIcms;
    private javax.swing.JMenu jMnNotas;
    private javax.swing.JMenu jMnSobre;
    private javax.swing.JMenu jMnTabelas;
    private javax.swing.JMenu jMnTransporte;
    private javax.swing.JMenuItem jMnUtilAssuntos;
    private javax.swing.JMenu jMnUtilitários;
    private javax.swing.JMenuItem jMniArquivo;
    private javax.swing.JMenuItem jMniAssuntos;
    private javax.swing.JMenuItem jMniCadastro;
    private javax.swing.JMenuItem jMniCapas;
    private javax.swing.JMenuItem jMniDepartamentos;
    private javax.swing.JMenuItem jMniDescarte;
    private javax.swing.JMenuItem jMniDevolucao;
    private javax.swing.JMenuItem jMniExtracao;
    private javax.swing.JMenuItem jMniLimpaMemorandos;
    private javax.swing.JMenuItem jMniLimpaPessoas;
    private javax.swing.JMenuItem jMniLimpraNFMem;
    private javax.swing.JMenuItem jMniLimpraNfProp;
    private javax.swing.JMenuItem jMniLocais;
    private javax.swing.JMenuItem jMniMemorandos;
    private javax.swing.JMenuItem jMniMovimento;
    private javax.swing.JMenuItem jMniPessoas;
    private javax.swing.JMenuItem jMniRelCapas;
    private javax.swing.JMenuItem jMniRelEtiquetas;
    private javax.swing.JMenuItem jMniRelNF;
    private javax.swing.JMenuItem jMniRelPaises;
    private javax.swing.JMenuItem jMniSair;
    private javax.swing.JMenuItem jMniTipos;
    private javax.swing.JMenu jMnuArquivoMorto;
    private javax.swing.JMenu jMnuSeguros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JTextField jTxtContCapas;
    private javax.swing.JTextField jTxtContEtiquetas;
    private javax.swing.JTextField jTxtContMem;
    private javax.swing.JTextField jTxtContNfC;
    private javax.swing.JTextField jTxtContNfP;
    private static javax.swing.JTextField jTxtUsuario;
    private javax.swing.JTextField jTxtVersao;
    // End of variables declaration//GEN-END:variables

    public void controlaAcesso() {
        String grupo = "";
        
        cn.conecta();
        cn.executeConsulta("SELECT grupo FROM cad_usuarios WHERE id = " + usuariosys + ";");
        try {
            while (cn.rs.next()) {
                grupo = cn.rs.getString("grupo");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível estabelecer o padrão de acesso");
            System.exit(0);
        }
        cn.desconecta();
        
        if ("2".equals(grupo)) {
            jMnEstabelecimentos.setEnabled(false);
            jMniCadastro.setEnabled(false);
            jMnNotas.setEnabled(false);
            jMnCadastros.setEnabled(false);
            jMniPessoas.setEnabled(false);
            jMniMemorandos.setEnabled(false);
            jMnuSeguros.setEnabled(false);
            jMnIcms.setEnabled(false);
            jMnConsultas.setEnabled(false);
            jMnConfiguracao.setEnabled(false);
            
            jMniTipos.setEnabled(false);
            jMniAssuntos.setEnabled(false);
            jMniDepartamentos.setEnabled(false);
            jMniLocais.setEnabled(false);
            jMniCapas.setEnabled(true);
            jMniMovimento.setEnabled(true);
            jMniExtracao.setEnabled(false);
            jMniDevolucao.setEnabled(false);
            jMniDescarte.setEnabled(false);
            
            jMnUtilAssuntos.setEnabled(false);
            
            jMniRelNF.setEnabled(false);
            jMniRelPaises.setEnabled(false);
            jMniRelCapas.setEnabled(false);
        } else if ("3".equals(grupo)) {
            jMnEstabelecimentos.setEnabled(false);
            jMniCadastro.setEnabled(false);
            jMnNotas.setEnabled(false);
            jMnCadastros.setEnabled(false);
            jMniPessoas.setEnabled(false);
            //jMniMemorandos.setEnabled(false);
            jMnuSeguros.setEnabled(false);
            jMnIcms.setEnabled(false);
            jMnConsultas.setEnabled(false);
            jMnuArquivoMorto.setEnabled(false);
            jMnConfiguracao.setEnabled(false);
            
            jMniTipos.setEnabled(false);
            jMniAssuntos.setEnabled(false);
            jMniDepartamentos.setEnabled(false);
            jMniLocais.setEnabled(false);
            jMniCapas.setEnabled(false);
            jMniMovimento.setEnabled(false);
            jMniExtracao.setEnabled(false);
            jMniDevolucao.setEnabled(false);
            jMniDescarte.setEnabled(false);
            
            jMnUtilAssuntos.setEnabled(false);
            
            jMniRelNF.setEnabled(false);
            jMniRelPaises.setEnabled(false);
            jMniRelCapas.setEnabled(false);
        }
        
    }
    
    private void abreTelaInterna(JInternalFrame tela) {
        
        try {
            //PREPARAÇÃO PARA RECEBER INSTRUÇÕES PARA NAO ABRIR VÁRIAS JANELAS
            if (false) {
                tela.setSelected(true);
            } else {
                tela.setVisible(true);
                jDPTelaPrincipal.add(tela);
                tela.setSelected(true);
                setPosicao(tela);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! Não foi possível abrir a tela '" + tela + "'. \nErro: " + e);
        }
    }
    
    private void setPosicao(JInternalFrame x) {
        Dimension d = x.getDesktopPane().getSize();
        x.setLocation((d.width - x.getSize().width) / 2, (d.height - x.getSize().height) / 2);
    }
}
