
package wsSpedProducao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CadConsultaCadastro2Soap12", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CadConsultaCadastro2Soap12 {


    /**
     * Consulta Cadastro de Contribuintes do ICMS
     * 
     * @param nfeDadosMsg
     * @return
     *     returns wsSpedCadastro.ConsultaCadastro2Response.ConsultaCadastro2Result
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2/consultaCadastro2")
    @WebResult(name = "consultaCadastro2Result", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2")
    @RequestWrapper(localName = "consultaCadastro2", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2", className = "wsSpedCadastro.ConsultaCadastro2")
    @ResponseWrapper(localName = "consultaCadastro2Response", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2", className = "wsSpedCadastro.ConsultaCadastro2Response")
    public wsSpedCadastro.ConsultaCadastro2Response.ConsultaCadastro2Result consultaCadastro2(
        @WebParam(name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2")
        wsSpedCadastro.ConsultaCadastro2 .NfeDadosMsg nfeDadosMsg);

}
