/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.icms;

import conexoes.ConexaoMySQL;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import ferramenta.JNumberFormatField99;

/**
 *
 * @author luiz.barcellos
 */
public class Icms_sc_nf_saidas extends javax.swing.JInternalFrame {

    private int var_consulta;

    ConexaoMySQL cn = new ConexaoMySQL();

    DateFormat dateOut = new SimpleDateFormat("yyyy/MM/dd");
    DateFormat dateIn = new SimpleDateFormat("dd/MM/yyyy");

    DecimalFormat df = new DecimalFormat("#,##0.00");
    private MaskFormatter data;

    /**
     * Creates new form Icms_sc_nf_saidas
     */
    public Icms_sc_nf_saidas() {
        try {
            data = new javax.swing.text.MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        initComponents();
        montaTabelaNF();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPesquisar1 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jTxtPesquisa_Multi1 = new javax.swing.JTextField();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTblConsulta_Multi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtIdEstabelecimento = new javax.swing.JTextField();
        jTxtNomeEstabelecimento = new javax.swing.JTextField();
        jTxtIdProdutor = new javax.swing.JTextField();
        jTxtNomeProdutor = new javax.swing.JTextField();
        jTxtId = new javax.swing.JTextField();
        jBtnPesquisar = new javax.swing.JButton();
        jTxtNotaFiscal = new javax.swing.JTextField();
        jTxtIdEmitente = new javax.swing.JTextField();
        jTxtNomeEmitente = new javax.swing.JTextField();
        jBtnPesquisaEmitente = new javax.swing.JButton();
        jCbTipo = new javax.swing.JComboBox<>();
        jSpData = new javax.swing.JFormattedTextField(data);
        jSpValor = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
        jSpCredito = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblNotasFiscais = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTxtSomaValor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtSomaCredito = new javax.swing.JTextField();
        jBtnExcluiNf = new javax.swing.JButton();
        jBtnIncluiNf = new javax.swing.JButton();

        jPesquisar1.setTitle("Pesquisar");
        jPesquisar1.setMinimumSize(new java.awt.Dimension(700, 400));

        jTxtPesquisa_Multi1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtPesquisa_Multi1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtPesquisa_Multi1KeyReleased(evt);
            }
        });

        jBtnConfirmar.setText("Adicionar");
        jBtnConfirmar.setEnabled(false);
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jTblConsulta_Multi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTblConsulta_Multi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblConsulta_Multi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblConsulta_MultiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTblConsulta_MultiMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(jTblConsulta_Multi);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 453, Short.MAX_VALUE)
                        .addComponent(jBtnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnConfirmar))
                    .addComponent(jTxtPesquisa_Multi1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTxtPesquisa_Multi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPesquisar1Layout = new javax.swing.GroupLayout(jPesquisar1.getContentPane());
        jPesquisar1.getContentPane().setLayout(jPesquisar1Layout);
        jPesquisar1Layout.setHorizontalGroup(
            jPesquisar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPesquisar1Layout.setVerticalGroup(
            jPesquisar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Relação de Notas de Entrada");

        jLabel1.setText("Produtor");

        jLabel2.setText("Estabelecimento");

        jLabel3.setText("Nota Fiscal");

        jLabel4.setText("Data Emissão");

        jLabel5.setText("Emitente");

        jLabel6.setText("Valor da Nota");

        jLabel7.setText("Valor do Crédito");

        jLabel8.setText("Requerimento");

        jTxtIdEstabelecimento.setEnabled(false);

        jTxtNomeEstabelecimento.setEnabled(false);

        jTxtIdProdutor.setEnabled(false);
        jTxtIdProdutor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdProdutorFocusLost(evt);
            }
        });

        jTxtNomeProdutor.setEnabled(false);

        jTxtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdFocusLost(evt);
            }
        });

        jBtnPesquisar.setText("...");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jTxtIdEmitente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdEmitenteFocusLost(evt);
            }
        });

        jTxtNomeEmitente.setEnabled(false);

        jBtnPesquisaEmitente.setText("...");
        jBtnPesquisaEmitente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisaEmitenteActionPerformed(evt);
            }
        });

        jCbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Energia Elétrica", "Maquinário", "Insumos", "Peças", "Diesel" }));

        jSpCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSpCreditoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(29, 29, 29)
                        .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTxtIdEmitente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTxtNomeEmitente, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(jBtnPesquisaEmitente))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTxtNotaFiscal, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                            .addComponent(jSpValor))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSpData)
                                            .addComponent(jSpCredito, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jCbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtIdProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNomeProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtIdEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNomeEstabelecimento)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesquisar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtIdProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtIdEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jTxtNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jSpValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtIdEmitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeEmitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesquisaEmitente))
                .addGap(45, 45, 45))
        );

        jTblNotasFiscais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblNotasFiscais);

        jLabel9.setText("Valor");

        jTxtSomaValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtSomaValor.setText("0.00");
        jTxtSomaValor.setEnabled(false);

        jLabel10.setText("Crédito");

        jTxtSomaCredito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtSomaCredito.setText("0.00");
        jTxtSomaCredito.setEnabled(false);

        jBtnExcluiNf.setText("Excluir");
        jBtnExcluiNf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluiNfActionPerformed(evt);
            }
        });

        jBtnIncluiNf.setText("Incluir");
        jBtnIncluiNf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluiNfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtSomaValor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jTxtSomaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnExcluiNf, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnIncluiNf, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxtSomaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTxtSomaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnExcluiNf)
                    .addComponent(jBtnIncluiNf))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtPesquisa_Multi1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPesquisa_Multi1KeyReleased
        montaLista();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPesquisa_Multi1KeyReleased

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        IncluiPesquisa();
        jPesquisar1.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        jPesquisar1.setVisible(false);        // TODO add your handling code here:
        jPesquisar1.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTblConsulta_MultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseClicked
        jBtnConfirmar.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jTblConsulta_MultiMouseClicked

    private void jTblConsulta_MultiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTblConsulta_MultiMouseEntered

    private void jBtnPesquisaEmitenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisaEmitenteActionPerformed
        var_consulta = 4;

        jPesquisar1.setVisible(true);

        montaLista();
    }//GEN-LAST:event_jBtnPesquisaEmitenteActionPerformed

    private void jTxtIdProdutorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdProdutorFocusLost
        var_consulta = 22;

        IncluiPesquisa();
    }//GEN-LAST:event_jTxtIdProdutorFocusLost

    private void jTxtIdEmitenteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdEmitenteFocusLost
        if (!"".equals(jTxtIdEmitente.getText())) {

            var_consulta = 44;
            IncluiPesquisa();
        }
    }//GEN-LAST:event_jTxtIdEmitenteFocusLost

    private void jBtnIncluiNfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluiNfActionPerformed
        String id = jTxtId.getText();
        String nf = jTxtNotaFiscal.getText();
        String tipo_Produto = jCbTipo.getSelectedItem().toString();
        Date data = null;
        Double valor = Double.parseDouble(jSpValor.getText().replace(".", "").replace(",", "."));
        Double credito = Double.parseDouble(jSpCredito.getText().replace(".", "").replace(",", "."));
        String emitente = jTxtIdEmitente.getText();
        String sql;

        try {
            data = dateIn.parse(jSpData.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        cn.conecta();
        sql = "INSERT INTO produtor_icms_notas (id,tipo_produto,nro_nf,"
                + "dt_emissao,valor_nf,valor_credito,id_emitente) "
                + "VALUES ('" + id + "','" + tipo_Produto + "','" + nf + "',"
                + "'" + dateOut.format(data) + "',"
                + "'" + valor + "','" + credito + "','" + emitente + "');";
        cn.executeAtualizacao(sql);
        cn.desconecta();

        if (ConexaoMySQL.resultadoUpd < 1) {

            mostraNF();
            limpaCampos();
        }


    }//GEN-LAST:event_jBtnIncluiNfActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        var_consulta = 1;
        jPesquisar1.setVisible(true);
        montaLista();
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jTxtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdFocusLost
        if (!"".equals(jTxtId.getText())) {
            var_consulta = 11;
            IncluiPesquisa();
        }
    }//GEN-LAST:event_jTxtIdFocusLost

    private void jBtnExcluiNfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluiNfActionPerformed
        int linha = jTblNotasFiscais.getSelectedRow();

        String id = jTxtId.getText();
        String nro = jTblNotasFiscais.getValueAt(linha, 0).toString();
        String emissor = jTblNotasFiscais.getValueAt(linha, 4).toString();

        cn.conecta();
        cn.executeAtualizacao("DELETE FROM produtor_icms_notas WHERE id = " + id + " AND nro_nf = " + nro + " AND id_emitente = " + emissor);
        cn.desconecta();

        mostraNF();

    }//GEN-LAST:event_jBtnExcluiNfActionPerformed

    private void jSpCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSpCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpCreditoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluiNf;
    private javax.swing.JButton jBtnIncluiNf;
    private javax.swing.JButton jBtnPesquisaEmitente;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<String> jCbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JFrame jPesquisar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jSpCredito;
    private javax.swing.JFormattedTextField jSpData;
    private javax.swing.JTextField jSpValor;
    private javax.swing.JTable jTblConsulta_Multi;
    private javax.swing.JTable jTblNotasFiscais;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtIdEmitente;
    private javax.swing.JTextField jTxtIdEstabelecimento;
    private javax.swing.JTextField jTxtIdProdutor;
    private javax.swing.JTextField jTxtNomeEmitente;
    private javax.swing.JTextField jTxtNomeEstabelecimento;
    private javax.swing.JTextField jTxtNomeProdutor;
    private javax.swing.JTextField jTxtNotaFiscal;
    private javax.swing.JTextField jTxtPesquisa_Multi1;
    private javax.swing.JTextField jTxtSomaCredito;
    private javax.swing.JTextField jTxtSomaValor;
    // End of variables declaration//GEN-END:variables

    private void habilitarEdicao() {
        //HABILITA CAMPOS DE TEXTO
        jTxtId.setEnabled(false);
        jTxtIdProdutor.setEnabled(true);
        jTxtIdEstabelecimento.setEnabled(true);
        jTxtNotaFiscal.setEnabled(true);
        jSpData.setEnabled(true);
        jSpValor.setEnabled(true);
        jSpCredito.setEnabled(true);
        jTxtIdEmitente.setEnabled(true);

        //HABILITA BOTOES
        jBtnPesquisar.setEnabled(false);
        jBtnPesquisaEmitente.setEnabled(true);
        jBtnExcluiNf.setEnabled(true);
        jBtnIncluiNf.setEnabled(true);

        //HABILITA TABELA
        jTblNotasFiscais.setEnabled(true);

    }

    private void desabilitarEdicao() {
        //HABILITA CAMPOS DE TEXTO
        jTxtId.setEnabled(true);
        jTxtIdProdutor.setEnabled(false);
        jTxtIdEstabelecimento.setEnabled(false);
        jTxtNotaFiscal.setEnabled(false);
        jSpData.setEnabled(false);
        jSpValor.setEnabled(false);
        jSpCredito.setEnabled(false);
        jTxtIdEmitente.setEnabled(false);

        //HABILITA BOTOES
        jBtnPesquisar.setEnabled(true);
        jBtnPesquisaEmitente.setEnabled(false);
        jBtnExcluiNf.setEnabled(false);
        jBtnIncluiNf.setEnabled(false);

        //HABILITA TABELA
        jTblNotasFiscais.setEnabled(false);
    }

    private void IncluiPesquisa() {
        String id;
        String sql;

        int linha = jTblConsulta_Multi.getSelectedRow();

        switch (var_consulta) {

            case 1:

                jTxtId.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());

            case 11:
                id = jTxtId.getText();
                jTxtIdEstabelecimento.setText("");
                jTxtIdProdutor.setText("");

                cn.conecta();

                try {
                    cn.executeConsulta("SELECT * FROM produtor_icms WHERE id = " + id);
                    while (cn.rs.next()) {
                        jTxtIdEstabelecimento.setText(cn.rs.getString("id_estabelecimento"));
                        jTxtIdProdutor.setText(cn.rs.getString("id_produtor"));
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex);
                }
                cn.desconecta();

                if (!"".equals(jTxtIdProdutor.getText())) {
                    var_consulta = 22;
                    IncluiPesquisa();
                    var_consulta = 33;
                    IncluiPesquisa();

                    mostraNF();
                }

                break;

            case 2:
                jTxtIdProdutor.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());

            case 22:

                id = jTxtIdProdutor.getText();

                cn.conecta();

                try {
                    cn.executeConsulta("SELECT nome FROM cad_pessoas WHERE id = " + id);
                    while (cn.rs.next()) {
                        jTxtNomeProdutor.setText(cn.rs.getString(1));
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex);
                }
                cn.desconecta();

                break;

            case 3:
                jTxtIdEstabelecimento.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());

            case 33:
                id = jTxtIdEstabelecimento.getText();

                cn.conecta();
                try {
                    cn.executeConsulta("SELECT concat(endereco, ', Inscrição Estadual ', inscri_est) FROM icms_estabelecimentos WHERE id = " + id);
                    while (cn.rs.next()) {
                        jTxtNomeEstabelecimento.setText(cn.rs.getString(1));
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex);
                }

                cn.desconecta();

                break;
            case 4:

                jTxtIdEmitente.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());

            case 44:
                id = jTxtIdEmitente.getText();

                cn.conecta();
                try {
                    cn.executeConsulta("SELECT nome FROM cad_pessoas WHERE id = " + id);
                    while (cn.rs.next()) {
                        jTxtNomeEmitente.setText(cn.rs.getString(1));
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex);
                }

                cn.desconecta();
        }
    }

    private void montaLista() {
        DefaultTableModel lista = (DefaultTableModel) jTblConsulta_Multi.getModel();
        lista.setColumnCount(0);  //limpa a tabela
        lista.setRowCount(0);     //limpa a tabela

        String sql;
        String id;

        switch (var_consulta) {
            case 1:
                lista.addColumn("Id");
                lista.addColumn("Nome");
                lista.addColumn("Processo");

                jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(60);

                jTxtPesquisa_Multi1.grabFocus();

                cn.conecta();

                if (!"".equals(jTxtPesquisa_Multi1.getText())) {
                    sql = " SELECT a.id, b.nome, c.inscri_est, a.dt_inicio_processo "
                            + "FROM produtor_icms a left join cad_pessoas b on (b.id = a.id_produtor) "
                            + "left join icms_estabelecimentos c on (c.id = a.id_estabelecimento) "
                            + "WHERE UPPER(b.nome) "
                            + "LIKE '%" + jTxtPesquisa_Multi1.getText().toUpperCase() + "%'"
                            + "OR UPPER(c.inscri_est) "
                            + "LIKE '%" + jTxtPesquisa_Multi1.getText().toUpperCase() + "%'"
                            + " ORDER BY b.nome";

                    cn.executeConsulta(sql);

                    try {
                        while (cn.rs.next()) {

                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("nome"),
                                "Processo da I.E. " + cn.rs.getString("inscri_est") + "iniciado em " + cn.rs.getString("dt_inicio_processo"),});
                        }
                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                    }

                } else { //Configuração para quando não há texto no campo pesquisa
                    sql = "SELECT a.id, b.nome, c.inscri_est, "
                            + "a.dt_inicio_processo FROM produtor_icms a "
                            + "left join cad_pessoas b on (b.id = a.id_produtor) "
                            + "left join icms_estabelecimentos c on (c.id = a.id_estabelecimento) "
                            + " ORDER BY b.nome";

                    cn.executeConsulta(sql);

                    try {
                        while (cn.rs.next()) {

                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("nome"),
                                "Processo da I.E. " + cn.rs.getString("inscri_est") + "iniciado em " + cn.rs.getString("dt_inicio_processo"),});

                        }
                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                    }

                    //Configuração dos botões, quando não há pesquisa
                }

                cn.desconecta();
                jBtnConfirmar.setEnabled(true);

                break;

            case 2:
                lista.addColumn("Id");
                lista.addColumn("Nome");
                lista.addColumn("CNPJ");
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(60);

                jTxtPesquisa_Multi1.grabFocus();

                cn.conecta();

                if (!"".equals(jTxtPesquisa_Multi1.getText())) {
                    sql = "SELECT * FROM cad_pessoas "
                            + "WHERE UPPER(nome) "
                            + "LIKE '%" + jTxtPesquisa_Multi1.getText().toUpperCase() + "%'"
                            + "OR UPPER(inscricao_federal) "
                            + "LIKE '%" + jTxtPesquisa_Multi1.getText().toUpperCase() + "%'"
                            + " ORDER BY nome";

                    cn.executeConsulta(sql);

                    try {
                        while (cn.rs.next()) {

                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("nome"),
                                cn.rs.getString("inscricao_federal")});
                        }
                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                    }

                } else { //Configuração para quando não há texto no campo pesquisa
                    sql = "SELECT * FROM cad_pessoas "
                            + " ORDER BY nome";

                    cn.executeConsulta(sql);

                    try {
                        while (cn.rs.next()) {

                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("nome"),
                                cn.rs.getString("inscricao_federal")});

                        }
                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                    }

                    //Configuração dos botões, quando não há pesquisa
                }

                cn.desconecta();
                jBtnConfirmar.setEnabled(true);
                break;

            case 3:
                id = jTxtIdProdutor.getText();

                lista.addColumn("Id");
                lista.addColumn("Descrição");
                lista.addColumn("Endereço");
                lista.addColumn("Inscrição Estadual");
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(60);

                jTxtPesquisa_Multi1.grabFocus();

                cn.conecta();

                if (!"".equals(jTxtPesquisa_Multi1.getText())) {
                    sql = "SELECT id, descricao, endereco, numero, municipio, inscri_est "
                            + "FROM icms_estabelecimentos "
                            + "WHERE id_pessoa = '" + id + "' "
                            + "AND UPPER(descricao) "
                            + "LIKE '%" + jTxtPesquisa_Multi1.getText().toUpperCase() + "%' "
                            + "OR UPPER(inscri_est) "
                            + "LIKE '%" + jTxtPesquisa_Multi1.getText().toUpperCase() + "%' "
                            + " ORDER BY descricao";

                    cn.executeConsulta(sql);

                    try {
                        while (cn.rs.next()) {

                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("descricao"),
                                cn.rs.getString("endereco") + ", " + cn.rs.getString("numero") + ", " + cn.rs.getString("municipio"),
                                cn.rs.getString("inscri_est")});
                        }
                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                    }

                } else { //Configuração para quando não há texto no campo pesquisa
                    sql = "SELECT id, descricao, endereco, numero, municipio, inscri_est "
                            + "FROM icms_estabelecimentos "
                            + "WHERE id_pessoa = '" + id + "' "
                            + " ORDER BY descricao";

                    cn.executeConsulta(sql);

                    try {
                        while (cn.rs.next()) {

                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("descricao"),
                                cn.rs.getString("endereco") + ", " + cn.rs.getString("numero") + ", " + cn.rs.getString("municipio"),
                                cn.rs.getString("inscri_est")});

                        }
                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                    }

                    //Configuração dos botões, quando não há pesquisa
                }

                cn.desconecta();
                jBtnConfirmar.setEnabled(true);

            case 33:
                break;

            case 4:
                lista.addColumn("Id");
                lista.addColumn("Nome");
                lista.addColumn("CNPJ");
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(60);

                jTxtPesquisa_Multi1.grabFocus();

                cn.conecta();

                if (!"".equals(jTxtPesquisa_Multi1.getText())) {
                    sql = "SELECT * FROM cad_pessoas "
                            + "WHERE UPPER(nome) "
                            + "LIKE '%" + jTxtPesquisa_Multi1.getText().toUpperCase() + "%'"
                            + "OR UPPER(inscricao_federal) "
                            + "LIKE '%" + jTxtPesquisa_Multi1.getText().toUpperCase() + "%'"
                            + " ORDER BY nome";

                    cn.executeConsulta(sql);

                    try {
                        while (cn.rs.next()) {

                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("nome"),
                                cn.rs.getString("inscricao_federal")});
                        }
                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                    }

                } else { //Configuração para quando não há texto no campo pesquisa
                    sql = "SELECT * FROM cad_pessoas "
                            + " ORDER BY nome";

                    cn.executeConsulta(sql);

                    try {
                        while (cn.rs.next()) {

                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("nome"),
                                cn.rs.getString("inscricao_federal")});

                        }
                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                    }

                    //Configuração dos botões, quando não há pesquisa
                }

                cn.desconecta();
                jBtnConfirmar.setEnabled(true);
            case 44:
                break;
        }
    }

    private void montaTabelaNF() {
        DefaultTableModel lista = (DefaultTableModel) jTblNotasFiscais.getModel();
        lista.setColumnCount(0);
        lista.setRowCount(0);

        lista.addColumn("Número");
        lista.addColumn("Emitente");
        lista.addColumn("Valor");
        lista.addColumn("Crédito");
        lista.addColumn("emissor");

        jTblNotasFiscais.getColumnModel().getColumn(0).setMaxWidth(100);
        jTblNotasFiscais.getColumnModel().getColumn(0).setMinWidth(100);
        jTblNotasFiscais.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(100);
        jTblNotasFiscais.getTableHeader().getColumnModel().getColumn(0).setMinWidth(100);
        jTblNotasFiscais.getColumnModel().getColumn(2).setMaxWidth(100);
        jTblNotasFiscais.getColumnModel().getColumn(2).setMinWidth(100);
        jTblNotasFiscais.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(100);
        jTblNotasFiscais.getTableHeader().getColumnModel().getColumn(2).setMinWidth(100);
        jTblNotasFiscais.getColumnModel().getColumn(3).setMaxWidth(100);
        jTblNotasFiscais.getColumnModel().getColumn(3).setMinWidth(100);
        jTblNotasFiscais.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(100);
        jTblNotasFiscais.getTableHeader().getColumnModel().getColumn(3).setMinWidth(100);
        jTblNotasFiscais.getColumnModel().getColumn(4).setMaxWidth(0);
        jTblNotasFiscais.getColumnModel().getColumn(4).setMinWidth(0);
        jTblNotasFiscais.getTableHeader().getColumnModel().getColumn(4).setMaxWidth(0);
        jTblNotasFiscais.getTableHeader().getColumnModel().getColumn(4).setMinWidth(0);

    }

    private void mostraNF() {
        DefaultTableModel lista = (DefaultTableModel) jTblNotasFiscais.getModel();
        lista.setRowCount(0);

        Double valor = 0.00;
        Double credito = 0.00;

        cn.conecta();
        cn.executeConsulta("SELECT a.nro_nf,b.nome as emitente, "
                + "a.valor_nf as valor, a.valor_credito as credito, "
                + "a.id_emitente "
                + "FROM produtor_icms_notas a "
                + "left join cad_pessoas b on (b.id = a.id_emitente) "
                + "WHERE a.id = " + jTxtId.getText() + ";");
        try {
            while (cn.rs.next()) {
                lista.addRow(new String[]{
                    cn.rs.getString("nro_nf"),
                    cn.rs.getString("emitente"),
                    df.format(cn.rs.getDouble("valor")),
                    df.format(cn.rs.getDouble("credito")),
                    cn.rs.getString("id_emitente")
                });
                valor += cn.rs.getDouble("valor");
                credito += cn.rs.getDouble("credito");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        cn.desconecta();

        jTxtSomaValor.setText(df.format(valor) + "");
        jTxtSomaCredito.setText(df.format(credito) + "");
    }

    private void limpaCampos() {
        jTxtNotaFiscal.setText("");
        jSpValor.setText("");
        jSpCredito.setText("");
        jTxtIdEmitente.setText("");
        jTxtNomeEmitente.setText("");
        jSpData.setValue(null);
    }
}
