/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.icms;

import conexoes.ConexaoMySQL;
import ferramenta.FiltrarTabela;
import ferramenta.ValidaCampoVazio;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luiz.barcellos
 */
public class IcmsFrota extends javax.swing.JInternalFrame {

    private int var_consulta;
    private String sql;
    private final ConexaoMySQL cn = new ConexaoMySQL();
    private javax.swing.text.MaskFormatter data;
    private DateFormat dateIn = new SimpleDateFormat("dd/MM/yyyy");
    private DateFormat dateOut = new SimpleDateFormat("yyyy/MM/dd");
    private final ValidaCampoVazio check = new ValidaCampoVazio();

    /**
     * Creates new form IcmsFrota
     */
    public IcmsFrota() {
        try {
            data = new javax.swing.text.MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(BaixaCreditos.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();

        montaTabelaFrotas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPesquisar = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jTxtPesquisa_Multi = new javax.swing.JTextField();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTblConsulta_Multi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtId = new ferramenta.JTextFieldSomenteNumeros();
        jLabel2 = new javax.swing.JLabel();
        jTxtNomeProdutor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTxtIdVeiculo = new javax.swing.JTextField();
        jTxtDescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtIdTipo = new ferramenta.JTextFieldSomenteNumeros();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtNroSerie = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTxtNomeTipo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtIdFabricante = new ferramenta.JTextFieldSomenteNumeros();
        jTxtNomeFabricante = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTxtDtAquisicao = new javax.swing.JFormattedTextField(data);
        jTxtDtAlienacao = new javax.swing.JFormattedTextField(data);
        jLabel9 = new javax.swing.JLabel();
        jTxtPlaca = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTxtChassi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtAno = new ferramenta.JTextFieldSomenteNumeros();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPesquisar.setTitle("Pesquisar");
        jPesquisar.setMinimumSize(new java.awt.Dimension(1200, 300));

        jTxtPesquisa_Multi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtPesquisa_Multi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtPesquisa_MultiKeyReleased(evt);
            }
        });

        jBtnConfirmar.setText("É esse aqui!!");
        jBtnConfirmar.setEnabled(false);
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Falha no engano :(");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jTblConsulta_Multi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblConsulta_Multi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblConsulta_MultiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTblConsulta_MultiMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(jTblConsulta_Multi);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 573, Short.MAX_VALUE)
                        .addComponent(jBtnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnConfirmar))
                    .addComponent(jTxtPesquisa_Multi)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTxtPesquisa_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPesquisarLayout = new javax.swing.GroupLayout(jPesquisar.getContentPane());
        jPesquisar.getContentPane().setLayout(jPesquisarLayout);
        jPesquisarLayout.setHorizontalGroup(
            jPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPesquisarLayout.setVerticalGroup(
            jPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Frota Produtor Rural");

        jLabel1.setText("Código");

        jTxtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdFocusLost(evt);
            }
        });

        jLabel2.setText("Produtor");

        jTxtNomeProdutor.setEnabled(false);

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtNomeProdutor))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2)
                .addComponent(jTxtNomeProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1))
        );

        jLabel3.setText("Id");

        jTxtIdVeiculo.setEnabled(false);

        jLabel4.setText("Descrição");

        jTxtIdTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdTipoFocusLost(evt);
            }
        });

        jLabel5.setText("Tipo");

        jLabel6.setText("Número de Série");

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTxtNomeTipo.setEnabled(false);

        jLabel7.setText("Fabricante");

        jTxtIdFabricante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdFabricanteFocusLost(evt);
            }
        });

        jTxtNomeFabricante.setEnabled(false);

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Data de Aquisição");

        jTxtDtAlienacao.setEnabled(false);

        jLabel9.setText("Data de Alienação");

        jLabel11.setText("Placa");

        jLabel12.setText("Chassi");

        jLabel10.setText("Ano de Fabricação");

        jCheckBox1.setText("Vendido");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtIdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNomeTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtChassi, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtIdFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNomeFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtIdVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtDtAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtDtAlienacao, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNroSerie)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtIdVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTxtIdFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)
                        .addComponent(jTxtNomeFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jTxtChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jTxtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTxtIdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)
                        .addComponent(jTxtNomeTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtNroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTxtDtAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtDtAlienacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jTxtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))))
        );

        jButton5.setText("Limpar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setText("Gravar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton4)
            .addComponent(jButton5)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdFocusLost
        if (!"".equals(jTxtId.getText())) {
            var_consulta = 111;
            incluiPesquisa();
        }

    }//GEN-LAST:event_jTxtIdFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        var_consulta = 1;
        jPesquisar.setVisible(true);
        jTxtPesquisa_Multi.setText("");
        montaLista();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTxtPesquisa_MultiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPesquisa_MultiKeyReleased
        new FiltrarTabela(jTblConsulta_Multi, jTxtPesquisa_Multi.getText());
    }//GEN-LAST:event_jTxtPesquisa_MultiKeyReleased

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        incluiPesquisa();
        jPesquisar.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        jPesquisar.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTblConsulta_MultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseClicked
        jBtnConfirmar.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jTblConsulta_MultiMouseClicked

    private void jTblConsulta_MultiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTblConsulta_MultiMouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        var_consulta = 2;
        jPesquisar.setVisible(true);
        montaLista();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        var_consulta = 3;
        jPesquisar.setVisible(true);
        montaLista();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        limpaCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String id = jTxtId.getText();
        String idVeiculo = jTxtIdVeiculo.getText();
        String descricao = jTxtDescricao.getText();
        String idTipo = jTxtIdTipo.getText();
        String ano = check.validar(jTxtAno.getText());
        String chassi = check.validar(jTxtChassi.getText());
        String idFab = jTxtIdFabricante.getText();
        String dtAquis = null;
        String dtAlien = null;
        String nroSerie = check.validar(jTxtNroSerie.getText());
        String placa = check.validar(jTxtPlaca.getText());

        //VERIFICA SE FOI INFORMADA UMA DATA DE AQUISIÇÃO
        if (!"  /  /    ".equals(jTxtDtAquisicao.getText())) {
            try {
                dtAquis = dateOut.format(dateIn.parse(jTxtDtAquisicao.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Não foi possível converter a data de Aquisição.");
            }
        }

        //VERIFICA SE FOI INFORMADA UMA DATA DE VENDA
        if (!"  /  /    ".equals(jTxtDtAlienacao.getText())) {
            try {
                dtAlien = dateOut.format(dateIn.parse(jTxtDtAlienacao.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Não foi possível converter a data de Alienação.");
            }
        }

        if ("".equals(jTxtIdVeiculo.getText())) {
            sql = "INSERT INTO produtor_imobilizado (ID_PRODUTOR, TIPO, DESCRICAO, "
                    + "NRO_SERIE, FABRICANTE, DATA_AQUISICAO, DATA_VENDA, "
                    + "ANO_FABRICACAO, PLACA, CHASSI) VALUES ('" + id + "',"
                    + "'" + idTipo + "','" + descricao + "'," + nroSerie + "," + idFab + ",";
            if (dtAquis == null) {
                sql += "null,";
            } else {
                sql += "'" + dtAquis + "',";
            }
            if (dtAlien == null) {
                sql += "null,";
            } else {
                sql += "'" + dtAlien + "',";
            }

            sql += ano + "," + placa + "," + chassi + ");";

        } else {

            sql = "UPDATE produtor_imobilizado SET tipo = '" + idTipo + "', "
                    + "descricao = '" + descricao + "', nro_serie = " + nroSerie + ","
                    + "fabricante = " + idFab + ",ano_fabricacao = " + ano + ", "
                    + "placa = " + placa + ", chassi = " + chassi + " ";

            if (dtAquis == null) {
                sql += ", data_aquisicao = null ";
            } else {
                sql += ", data_aquisicao = '" + dtAquis + "' ";
            }
            if (dtAlien == null) {
                sql += ", data_venda = null ";
            } else {
                sql += ", data_venda = '" + dtAlien + "' ";
            }

            sql += " WHERE id_produtor = '" + id + "' AND id = '" + idVeiculo + "';";

        }

        if (cn.conecta()) {
            try {
                if (cn.executeAtualizacao(sql)) {
                    limpaCampos();

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                cn.desconecta();
                montaTabelaFrotas();
                var_consulta = 11;
                incluiPesquisa();
            }

        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        if (jCheckBox1.isSelected()) {
            jTxtDtAlienacao.setEnabled(true);
        } else {
            jTxtDtAlienacao.setEnabled(false);
            jTxtDtAlienacao.setText("  /  /    ");

        }
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void jTxtIdTipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdTipoFocusLost
        if (!"".equals(jTxtIdTipo.getText())) {
            var_consulta = 22;
            incluiPesquisa();
        }
    }//GEN-LAST:event_jTxtIdTipoFocusLost

    private void jTxtIdFabricanteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdFabricanteFocusLost
        if (!"".equals(jTxtIdFabricante.getText())) {
            var_consulta = 33;
            incluiPesquisa();
        }
    }//GEN-LAST:event_jTxtIdFabricanteFocusLost

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int linha = jTable1.getSelectedRow();
        try {
            jTxtIdVeiculo.setText(jTable1.getValueAt(linha, 0).toString());
            jTxtIdTipo.setText(jTable1.getValueAt(linha, 1).toString());
            jTxtDescricao.setText(jTable1.getValueAt(linha, 2).toString());
            jTxtIdFabricante.setText(jTable1.getValueAt(linha, 4).toString());
            jTxtNroSerie.setText(jTable1.getValueAt(linha, 3).toString());
            jTxtDtAquisicao.setText(jTable1.getValueAt(linha, 5).toString());
            jTxtDtAlienacao.setText(jTable1.getValueAt(linha, 6).toString());
            jTxtAno.setText(jTable1.getValueAt(linha, 7).toString());
            jTxtPlaca.setText(jTable1.getValueAt(linha, 8).toString());
            jTxtChassi.setText(jTable1.getValueAt(linha, 9).toString());

            a
                    
                    //CORRIGIR SITUAÇÕES ONDE O VALOR É NULL
            
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e);
        }

        var_consulta = 33;
        incluiPesquisa();
        var_consulta = 22;
        incluiPesquisa();

    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JFrame jPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTblConsulta_Multi;
    private javax.swing.JTextField jTxtAno;
    private javax.swing.JTextField jTxtChassi;
    private javax.swing.JTextField jTxtDescricao;
    private javax.swing.JTextField jTxtDtAlienacao;
    private javax.swing.JTextField jTxtDtAquisicao;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtIdFabricante;
    private javax.swing.JTextField jTxtIdTipo;
    private javax.swing.JTextField jTxtIdVeiculo;
    private javax.swing.JTextField jTxtNomeFabricante;
    private javax.swing.JTextField jTxtNomeProdutor;
    private javax.swing.JTextField jTxtNomeTipo;
    private javax.swing.JTextField jTxtNroSerie;
    private javax.swing.JTextField jTxtPesquisa_Multi;
    private javax.swing.JTextField jTxtPlaca;
    // End of variables declaration//GEN-END:variables

    private void incluiPesquisa() {
        int linha = jTblConsulta_Multi.getSelectedRow();

        switch (var_consulta) {

            case 1:

                jTxtId.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());
                jTxtNomeProdutor.setText(jTblConsulta_Multi.getValueAt(linha, 1).toString());

            case 11:

                montaTabelaFrotas();

                DefaultTableModel lista = (DefaultTableModel) jTable1.getModel();

                sql = "SELECT * FROM PRODUTOR_IMOBILIZADO where ID_PRODUTOR = '" + jTxtId.getText() + "';";

                if (cn.conecta()) {
                    try {

                        cn.executeConsulta(sql);

                        while (cn.rs.next()) {

                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("tipo"),
                                cn.rs.getString("descricao"),
                                cn.rs.getString("nro_serie"),
                                cn.rs.getString("fabricante"),
                                cn.rs.getString("data_aquisicao"),
                                cn.rs.getString("data_venda"),
                                cn.rs.getString("ano_fabricacao"),
                                cn.rs.getString("placa"),
                                cn.rs.getString("chassi")
                            });
                        }
                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                    } finally {
                        cn.desconecta();
                    }
                }
                break;

            case 111:
                jTxtNomeProdutor.setText("");

                sql = "SELECT * FROM cad_pessoas "
                        + "WHERE ID IN (SELECT distinct id_produtor FROM CONTROLADORIA.produtor_icms) "
                        + "AND ID = '" + jTxtId.getText() + "';";

                if (cn.conecta()) {
                    try {
                        cn.executeConsulta(sql);
                        while (cn.rs.next()) {
                            jTxtNomeProdutor.setText(cn.rs.getString("Nome"));
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    } finally {
                        cn.desconecta();
                    }
                }

                if (!"".equals(jTxtNomeProdutor.getText())) {
                    var_consulta = 11;
                    incluiPesquisa();
                } else {
                    JOptionPane.showMessageDialog(null, "Produtor não encontrado.");
                    jTxtId.setText("");
                    jTxtId.grabFocus();
                }

                break;

            case 2:

                jTxtIdTipo.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());
                jTxtNomeTipo.setText(jTblConsulta_Multi.getValueAt(linha, 1).toString());

                break;

            case 22:

                jTxtNomeTipo.setText("");

                sql = "SELECT * FROM icms_tipos_veiculos "
                        + "where ID = '" + jTxtIdTipo.getText() + "';";

                if (cn.conecta()) {
                    try {
                        cn.executeConsulta(sql);
                        while (cn.rs.next()) {
                            jTxtNomeTipo.setText(cn.rs.getString("descricao"));
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    } finally {
                        cn.desconecta();
                    }
                }

                if ("".equals(jTxtNomeTipo.getText())) {
                    JOptionPane.showMessageDialog(null, "Tipo de veículo não encontrado.");
                    jTxtIdTipo.setText("");
                    jTxtIdTipo.grabFocus();
                }

                break;

            case 3:

                jTxtIdFabricante.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());
                jTxtNomeFabricante.setText(jTblConsulta_Multi.getValueAt(linha, 1).toString());

                break;

            case 33:

                jTxtNomeFabricante.setText("");

                sql = "SELECT * FROM icms_fabricantes "
                        + "where ID = '" + jTxtIdFabricante.getText() + "';";

                if (cn.conecta()) {
                    try {
                        cn.executeConsulta(sql);
                        while (cn.rs.next()) {
                            jTxtNomeFabricante.setText(cn.rs.getString("descricao"));
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    } finally {
                        cn.desconecta();
                    }
                }

                if ("".equals(jTxtNomeFabricante.getText())) {
                    JOptionPane.showMessageDialog(null, "Fabricante não encontrado.");
                    jTxtIdFabricante.setText("");
                    jTxtIdFabricante.grabFocus();
                }

                break;

        }

    }

    private void montaLista() {

        DefaultTableModel lista = (DefaultTableModel) jTblConsulta_Multi.getModel();

        lista.setColumnCount(0);
        lista.setRowCount(0);

        switch (var_consulta) {
            case 1:

                lista.addColumn("Id");
                lista.addColumn("Nome");
                lista.addColumn("CPF");

                jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(60);

                jTxtPesquisa_Multi.grabFocus();

                sql = "SELECT * FROM cad_pessoas WHERE ID IN (SELECT distinct id_produtor FROM CONTROLADORIA.produtor_icms) "
                        + " ORDER BY nome;";
                if (cn.conecta()) {

                    try {
                        cn.executeConsulta(sql);
                        while (cn.rs.next()) {

                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("nome"),
                                cn.rs.getString("inscricao_federal")});

                        }

                        jBtnConfirmar.setEnabled(true);

                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                    } finally {
                        cn.desconecta();
                    }
                    //Configuração dos botões, quando não há pesquisa
                }

                break;

            case 2:

                lista.addColumn("Id");
                lista.addColumn("Descrição");
                lista.addColumn("Observação");

                if (cn.conecta()) {
                    try {
                        String sql = "SELECT * FROM icms_tipos_veiculos "
                                + " ORDER BY descricao";

                        cn.executeConsulta(sql);

                        while (cn.rs.next()) {

                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("descricao"),
                                cn.rs.getString("observacao")});

                        }
                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                    } finally {
                        cn.desconecta();
                    }

                    jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(40);
                    jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(40);
                    jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(40);
                    jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(40);
                    jTblConsulta_Multi.getColumnModel().getColumn(1).setMaxWidth(160);
                    jTblConsulta_Multi.getColumnModel().getColumn(1).setMinWidth(160);
                    jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(160);
                    jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(1).setMinWidth(160);

                    //Configuração dos botões, quando não há pesquisa
                }

                jBtnConfirmar.setEnabled(true);

                break;

            case 3:

                lista.addColumn("Id");
                lista.addColumn("Descrição");
                lista.addColumn("Observação");

                if (cn.conecta()) {
                    try {
                        String sql = "SELECT * FROM icms_fabricantes "
                                + " ORDER BY descricao";

                        cn.executeConsulta(sql);

                        while (cn.rs.next()) {

                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("descricao"),
                                cn.rs.getString("observacao")});

                        }
                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                    } finally {
                        cn.desconecta();
                    }

                    jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(40);
                    jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(40);
                    jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(40);
                    jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(40);
                    jTblConsulta_Multi.getColumnModel().getColumn(1).setMaxWidth(160);
                    jTblConsulta_Multi.getColumnModel().getColumn(1).setMinWidth(160);
                    jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(160);
                    jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(1).setMinWidth(160);

                    break;

                }

        }
    }

    private void limpaCampos() {
        jTxtIdTipo.setText("");
        jTxtNomeTipo.setText("");
        jTxtIdFabricante.setText("");
        jTxtNomeFabricante.setText("");
        jTxtIdVeiculo.setText("");
        jTxtDescricao.setText("");
        jTxtAno.setText("");
        jTxtChassi.setText("");
        //jTxtDtAlienacao.setText("");
        ///jTxtDtAquisicao.setText("");
        jTxtNroSerie.setText("");
        jTxtPlaca.setText("");
    }

    private void montaTabelaFrotas() {

        DefaultTableModel frota = (DefaultTableModel) jTable1.getModel();

        frota.setColumnCount(0);
        frota.setRowCount(0);

        frota.addColumn("Id");
        frota.addColumn("Tipo");
        frota.addColumn("Descrição");
        frota.addColumn("Série");
        frota.addColumn("Fab");
        frota.addColumn("Aquisição");
        frota.addColumn("Venda");
        frota.addColumn("Ano");
        frota.addColumn("Placa");
        frota.addColumn("Chassi");

        jTable1.getColumnModel().getColumn(0).setMaxWidth(40);
        jTable1.getColumnModel().getColumn(0).setMinWidth(40);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(40);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMinWidth(40);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(40);
        jTable1.getColumnModel().getColumn(1).setMinWidth(40);
        jTable1.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(40);
        jTable1.getTableHeader().getColumnModel().getColumn(1).setMinWidth(40);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(40);
        jTable1.getColumnModel().getColumn(4).setMinWidth(40);
        jTable1.getTableHeader().getColumnModel().getColumn(4).setMaxWidth(40);
        jTable1.getTableHeader().getColumnModel().getColumn(4).setMinWidth(40);
        jTable1.getColumnModel().getColumn(7).setMaxWidth(40);
        jTable1.getColumnModel().getColumn(7).setMinWidth(40);
        jTable1.getTableHeader().getColumnModel().getColumn(7).setMaxWidth(40);
        jTable1.getTableHeader().getColumnModel().getColumn(7).setMinWidth(40);
        jTable1.getColumnModel().getColumn(3).setMaxWidth(100);
        jTable1.getColumnModel().getColumn(3).setMinWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(3).setMinWidth(100);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(100);
        jTable1.getColumnModel().getColumn(5).setMinWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(5).setMaxWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(5).setMinWidth(100);
        jTable1.getColumnModel().getColumn(6).setMaxWidth(100);
        jTable1.getColumnModel().getColumn(6).setMinWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(6).setMaxWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(6).setMinWidth(100);
        jTable1.getColumnModel().getColumn(8).setMaxWidth(100);
        jTable1.getColumnModel().getColumn(8).setMinWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(8).setMaxWidth(100);
        jTable1.getTableHeader().getColumnModel().getColumn(8).setMinWidth(100);

    }
}
