/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.icms;

import conexoes.ConexaoMySQL;
import ferramenta.FiltrarTabela;
import ferramenta.JNumberFormatField99;
import ferramenta.ValidaInscricao;
import java.text.ChoiceFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ferna
 */
public class icms_estabelecimentos extends javax.swing.JInternalFrame {

    private String sql;
    private ConexaoMySQL cn = new ConexaoMySQL();
    private int var_consulta;
    private String codAtual;
    private NumberFormat INTEGER_FORMAT = new DecimalFormat("#");
    private DecimalFormat df = new DecimalFormat("#,##0.00");
    private String inscr_est_atual;
    private ValidaInscricao valid = new ValidaInscricao();

    /**
     * Creates new form icms_estabelecimentos
     */
    public icms_estabelecimentos() {
        initComponents();
        montaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPesquisar = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jTxtPesquisa_Multi = new javax.swing.JTextField();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTblConsulta_Multi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtIdProd = new JNumberFormatField99(INTEGER_FORMAT);
        jTxtNomeProd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtIdArea = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtIE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCbUF = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTxtDescricao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtNirf = new JNumberFormatField99(INTEGER_FORMAT);
        jLabel7 = new javax.swing.JLabel();
        jTxtIncra = new JNumberFormatField99(INTEGER_FORMAT);
        jTxtMatricula = new JNumberFormatField99(INTEGER_FORMAT);
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtEndereco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtNumero = new javax.swing.JTextField();
        jTxtBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCbMunicipio = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jTxtArea = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAtividades = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jPesquisar.setTitle("Pesquisar");
        jPesquisar.setMinimumSize(new java.awt.Dimension(700, 400));

        jTxtPesquisa_Multi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtPesquisa_Multi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtPesquisa_MultiKeyReleased(evt);
            }
        });

        jBtnConfirmar.setText("Adicionar");
        jBtnConfirmar.setEnabled(false);
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jTblConsulta_Multi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTblConsulta_Multi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblConsulta_Multi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblConsulta_MultiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTblConsulta_MultiMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(jTblConsulta_Multi);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 453, Short.MAX_VALUE)
                        .addComponent(jBtnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnConfirmar))
                    .addComponent(jTxtPesquisa_Multi)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTxtPesquisa_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPesquisarLayout = new javax.swing.GroupLayout(jPesquisar.getContentPane());
        jPesquisar.getContentPane().setLayout(jPesquisarLayout);
        jPesquisarLayout.setHorizontalGroup(
            jPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPesquisarLayout.setVerticalGroup(
            jPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setTitle("Estabelecimentos por Produtor");

        jLabel1.setText("Produtor");

        jTxtIdProd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtIdProdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdProdFocusLost(evt);
            }
        });

        jTxtNomeProd.setEnabled(false);

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNomeProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jTxtIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTxtNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Estabelecimento"));

        jLabel2.setText("Código");

        jTxtIdArea.setEnabled(false);

        jLabel3.setText("Inscrição Estadual");

        jTxtIE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtIEFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIEFocusLost(evt);
            }
        });

        jLabel4.setText("UF");

        jCbUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        jLabel5.setText("Descrição");

        jLabel6.setText("NIRF");

        jLabel7.setText("Incra");

        jLabel8.setText("Matrícula");

        jLabel9.setText("Endereço");

        jLabel10.setText("Número");

        jLabel11.setText("Bairro");

        jLabel12.setText("Município");

        jCbMunicipio.setEnabled(false);

        jLabel13.setText("Área Total");

        jLabel14.setText("Atividades");

        jTxtAtividades.setColumns(20);
        jTxtAtividades.setRows(5);
        jScrollPane1.setViewportView(jTxtAtividades);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtIdArea, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbUF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtIE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtEndereco))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtDescricao)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtNirf, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtIncra, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel14))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtIdArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jCbUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTxtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtNirf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtIncra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jCbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton2.setText("Gravar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Limpar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2)
            .addComponent(jButton3)
            .addComponent(jButton4)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTxtPesquisa_MultiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPesquisa_MultiKeyReleased
        new FiltrarTabela(jTblConsulta_Multi, jTxtPesquisa_Multi.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPesquisa_MultiKeyReleased

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        incluiPesquisa();
        jPesquisar.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        jPesquisar.setVisible(false);        // TODO add your handling code here:
        jPesquisar.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTblConsulta_MultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseClicked
        jBtnConfirmar.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jTblConsulta_MultiMouseClicked

    private void jTblConsulta_MultiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseEntered

    }//GEN-LAST:event_jTblConsulta_MultiMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        var_consulta = 1;
        jPesquisar.setVisible(true);
        montaLista();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        limpaCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTxtIdProdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdProdFocusLost
        String cod = jTxtIdProd.getText();
        if ("".equals(cod)) {
            limpaCampos();
            jTxtNomeProd.setText("");
        } else if (!cod.equals(codAtual)) {
            var_consulta = 2;
            incluiPesquisa();
        }

    }//GEN-LAST:event_jTxtIdProdFocusLost

    private void jTxtIdProdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdProdFocusGained
        codAtual = jTxtIdProd.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIdProdFocusGained

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        selecionaEstab();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        gravar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTxtIEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIEFocusLost
        String iest = jTxtIE.getText();
        if (!iest.equals(inscr_est_atual)) {

            try {
                valid.validaIE(iest, jCbUF.getSelectedItem().toString());

                carregaMunicipios();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);

                jCbMunicipio.removeAllItems();

            }

        }
    }//GEN-LAST:event_jTxtIEFocusLost

    private void jTxtIEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIEFocusGained
        inscr_est_atual = jTxtIE.getText();
    }//GEN-LAST:event_jTxtIEFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jCbMunicipio;
    private javax.swing.JComboBox<String> jCbUF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JFrame jPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTblConsulta_Multi;
    private javax.swing.JTextField jTxtArea;
    private javax.swing.JTextArea jTxtAtividades;
    private javax.swing.JTextField jTxtBairro;
    private javax.swing.JTextField jTxtDescricao;
    private javax.swing.JTextField jTxtEndereco;
    private javax.swing.JTextField jTxtIE;
    private javax.swing.JTextField jTxtIdArea;
    private javax.swing.JTextField jTxtIdProd;
    private javax.swing.JTextField jTxtIncra;
    private javax.swing.JTextField jTxtMatricula;
    private javax.swing.JTextField jTxtNirf;
    private javax.swing.JTextField jTxtNomeProd;
    private javax.swing.JTextField jTxtNumero;
    private javax.swing.JTextField jTxtPesquisa_Multi;
    // End of variables declaration//GEN-END:variables

    private void incluiPesquisa() {

        switch (var_consulta) {
            case 1:
                int linha = jTblConsulta_Multi.getSelectedRow();

                jTxtIdProd.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());
                jTxtNomeProd.setText(jTblConsulta_Multi.getValueAt(linha, 1).toString());

                break;

            case 2:
                sql = "SELECT id, nome FROM controladoria.cad_pessoas "
                        + "WHERE id = '" + jTxtIdProd.getText() + "';";

                if (cn.conecta()) {
                    try {
                        cn.executeConsulta(sql);
                        while (cn.rs.next()) {
                            jTxtNomeProd.setText(cn.rs.getString("nome"));
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    } finally {
                        cn.desconecta();
                    }
                }
        }

        if (!"".equals(jTxtNomeProd.getText())) {

            DefaultTableModel lista = montaTabela();

            sql = "SELECT * FROM controladoria.icms_estabelecimentos a "
                    + "WHERE a.id_pessoa = '" + jTxtIdProd.getText() + "';";

            if (cn.conecta()) {
                try {
                    cn.executeConsulta(sql);
                    while (cn.rs.next()) {
                        lista.addRow(new String[]{
                            cn.rs.getString("id"),
                            cn.rs.getString("descricao"),
                            cn.rs.getString("nirf"),
                            cn.rs.getString("incra"),
                            cn.rs.getString("matricula"),
                            cn.rs.getString("endereco"),
                            cn.rs.getString("bairro"),
                            cn.rs.getString("municipio"),
                            cn.rs.getString("inscri_est"),
                            df.format(cn.rs.getDouble("total_area")),
                            cn.rs.getString("atividades"),
                            cn.rs.getString("numero")
                        });

                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                } finally {
                    cn.desconecta();
                }
            }

        }

    }

    private void montaLista() {

        DefaultTableModel lista = (DefaultTableModel) jTblConsulta_Multi.getModel();

        lista.setRowCount(0);
        lista.setColumnCount(0);

        lista.addColumn("Código");
        lista.addColumn("Nome");
        lista.addColumn("Inscrição Federal");

        sql = "SELECT * FROM controladoria.cad_pessoas a ORDER BY a.nome;";

        if (cn.conecta()) {
            try {
                cn.executeConsulta(sql);
                while (cn.rs.next()) {
                    lista.addRow(new String[]{
                        cn.rs.getString("id"),
                        cn.rs.getString("nome"),
                        cn.rs.getString("inscricao_federal"),});
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                cn.desconecta();
            }
        }

    }

    private void limpaCampos() {
        jTxtIdArea.setText("");
        jCbUF.setSelectedIndex(0);
        jTxtIE.setText("");
        jTxtDescricao.setText("");
        jTxtArea.setText("");
        jTxtNirf.setText("");
        jTxtIncra.setText("");
        jTxtMatricula.setText("");
        jTxtEndereco.setText("");
        jTxtNumero.setText("");
        jTxtBairro.setText("");
        jTxtAtividades.setText("");
        jCbMunicipio.removeAllItems();
        jCbMunicipio.setEnabled(false);
        jCbUF.setEnabled(true);
    }

    private DefaultTableModel montaTabela() {
        DefaultTableModel lista = (DefaultTableModel) jTable1.getModel();

        lista.setColumnCount(0);
        lista.setRowCount(0);

        lista.addColumn("Código");
        lista.addColumn("Descrição");
        lista.addColumn("Nirf");
        lista.addColumn("Incra");
        lista.addColumn("Matrícula");
        lista.addColumn("Endereço");
        lista.addColumn("Bairro");
        lista.addColumn("Município");
        lista.addColumn("Inscrição Estadual");
        lista.addColumn("Área Total");
        lista.addColumn("Atividades");
        lista.addColumn("Numero");

        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(2).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(2).setMinWidth(0);
        jTable1.getColumnModel().getColumn(3).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(3).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(3).setMinWidth(0);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(4).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(4).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(4).setMinWidth(0);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(5).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(5).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(5).setMinWidth(0);
        jTable1.getColumnModel().getColumn(6).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(6).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(6).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(6).setMinWidth(0);
        jTable1.getColumnModel().getColumn(9).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(9).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(9).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(9).setMinWidth(0);
        jTable1.getColumnModel().getColumn(10).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(10).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(10).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(10).setMinWidth(0);
        jTable1.getColumnModel().getColumn(11).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(11).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(11).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(11).setMinWidth(0);

        return lista;
    }

    private void selecionaEstab() {
        limpaCampos();
        
        int linha = jTable1.getSelectedRow();

        jTxtIdArea.setText(jTable1.getValueAt(linha, 0).toString());
        jTxtDescricao.setText(jTable1.getValueAt(linha, 1).toString());
        jTxtNirf.setText(jTable1.getValueAt(linha, 2).toString());
        jTxtIncra.setText(jTable1.getValueAt(linha, 3).toString());
        jTxtMatricula.setText(jTable1.getValueAt(linha, 4).toString());
        jTxtEndereco.setText(jTable1.getValueAt(linha, 5).toString());
        jTxtBairro.setText(jTable1.getValueAt(linha, 6).toString());
        jCbMunicipio.addItem(jTable1.getValueAt(linha, 7).toString());
        jCbMunicipio.setSelectedItem(jTable1.getValueAt(linha, 7).toString());
        jTxtIE.setText(jTable1.getValueAt(linha, 8).toString());
        jTxtArea.setText(jTable1.getValueAt(linha, 9).toString());
        jTxtAtividades.setText(jTable1.getValueAt(linha, 10).toString());
        jTxtNumero.setText(jTable1.getValueAt(linha, 11).toString());

        jCbUF.setSelectedIndex(-1);
        jCbUF.setEnabled(false);

    }

    private void gravar() {
        String idProd = jTxtIdProd.getText();
        String idArea = jTxtIdArea.getText();
        String inscrEst = jTxtIE.getText();
        String desc = jTxtDescricao.getText();
        String area = jTxtArea.getText().replace(".", "").replace(",", ".");
        String nirf = jTxtNirf.getText();
        String incra = jTxtIncra.getText();
        String matricula = jTxtMatricula.getText();
        String endereco = jTxtEndereco.getText();
        String numero = jTxtNumero.getText();
        String bairro = jTxtBairro.getText();
        String municipio = jCbMunicipio.getSelectedItem().toString();
        String atividades = jTxtAtividades.getText();

        if ("".equals(jTxtIdArea.getText())) {
            sql = "INSERT INTO controladoria.icms_estabelecimentos (id_pessoa, "
                    + "descricao, nirf, incra, matricula, endereco, numero, "
                    + "bairro, municipio, inscri_est, total_area, atividades) "
                    + "VALUES ('" + idProd + "','" + desc + "','" + nirf + "',"
                    + "'" + incra + "','" + matricula + "','" + endereco + "',"
                    + "'" + numero + "','" + bairro + "','" + municipio + "',"
                    + "'" + inscrEst + "','" + area + "','" + atividades + "');";
        } else {
            sql = "UPDATE controladoria.icms_estabelecimentos "
                    + "SET descricao = '" + desc + "', nirf = '" + nirf + "',"
                    + "incra = '" + incra + "', matricula = '" + matricula + "',"
                    + "endereco = '" + endereco + "', numero = '" + numero + "',"
                    + "bairro = '" + bairro + "', total_area = '" + area + "',"
                    + "atividades = '" + atividades + "' "
                    + "WHERE id = '" + idArea + "' AND id_pessoa = '" + idProd + "';";
        }

        if (cn.conecta()) {
            try {
                if (cn.executeAtualizacao(sql)) {
                    limpaCampos();
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                cn.desconecta();
            }
            var_consulta = 99; //index 99 não existe. só irá pesquisar novamente a tabela.
            incluiPesquisa();
        }

    }

    private void carregaMunicipios() {
        sql = "SELECT * FROM controladoria.cad_munic a "
                + "WHERE a.uf = '" + jCbUF.getSelectedItem() + "' "
                + "ORDER BY a.nome;";

        jCbMunicipio.removeAllItems();

        if (cn.conecta()) {
            try {
                cn.executeConsulta(sql);
                while (cn.rs.next()) {
                    jCbMunicipio.addItem(cn.rs.getString("nome"));
                }
                
                jCbUF.setEnabled(false);
                jCbMunicipio.setEnabled(true);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                cn.desconecta();
            }
        }
    }

}
