/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.icms;

import conexoes.ConexaoMySQL;
import ferramenta.ColorRender;
import ferramenta.IcmsProcessos;
import ferramenta.JNumberFormatField99;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luiz.barcellos
 */
public class IcmsAceiteCredito extends javax.swing.JInternalFrame {

    private int var_consulta;
    private String sql;
    private final ConexaoMySQL cn = new ConexaoMySQL();
    private final DecimalFormat df = new DecimalFormat("#,##0.00");
    private final DateFormat dateIn = new SimpleDateFormat("dd/MM/yyyy");
    private final IcmsProcessos proc = new IcmsProcessos();
    public static final double tolerancia = 0.000001;
    private boolean gravar;

    private Double vendas = 0.00, credito = 0.00, proporcao = 0.00, aproveitado = 0.00;

    /**
     * Creates new form IcmsAceiteCredito
     */
    public IcmsAceiteCredito() {
        initComponents();
        montaTblProdutos();
        montaTblNotas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPesquisar = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jTxtPesquisa_Multi = new javax.swing.JTextField();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTblConsulta_Multi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtNomeProdutor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            jTxtDataEmissao = new javax.swing.JFormattedTextField(data);
            jButton1 = new javax.swing.JButton();
            jPanel2 = new javax.swing.JPanel();
            jRbDeferido = new javax.swing.JRadioButton();
            jRbIndeferido = new javax.swing.JRadioButton();
            jTxtIE = new javax.swing.JTextField();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jTxtCreditoSolicitado = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
            jPanel3 = new javax.swing.JPanel();
            jLabel7 = new javax.swing.JLabel();
            jTxtInformacao = new javax.swing.JTextField();
            jTxtProcesso = new javax.swing.JTextField();
            jLabel8 = new javax.swing.JLabel();
            jLabel9 = new javax.swing.JLabel();
            jTxtDataAnalise = new javax.swing.JFormattedTextField(data);
            jLabel10 = new javax.swing.JLabel();
            jTxtCreditoLiberado = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
            jLabel11 = new javax.swing.JLabel();
            jTxtDtInicial = new javax.swing.JFormattedTextField(data);
            jTxtDtFinal = new javax.swing.JFormattedTextField(data);
            jLabel12 = new javax.swing.JLabel();
            jLabel13 = new javax.swing.JLabel();
            jTxtPercentual = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
            jLabel14 = new javax.swing.JLabel();
            jTxtVendas = new JNumberFormatField99(new DecimalFormat("#,##0.00"));
            jScrollPane1 = new javax.swing.JScrollPane();
            jTable1 = new javax.swing.JTable();
            jButton2 = new javax.swing.JButton();
            jButton3 = new javax.swing.JButton();
            jButton4 = new javax.swing.JButton();
            jScrollPane2 = new javax.swing.JScrollPane();
            jTable2 = new javax.swing.JTable();
            jButton5 = new javax.swing.JButton();
            jPanel4 = new javax.swing.JPanel();
            jButton6 = new javax.swing.JButton();
            jButton8 = new javax.swing.JButton();

            jPesquisar.setTitle("Pesquisar");
            jPesquisar.setMinimumSize(new java.awt.Dimension(400, 300));

            jTxtPesquisa_Multi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jTxtPesquisa_Multi.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jTxtPesquisa_MultiKeyReleased(evt);
                }
            });

            jBtnConfirmar.setText("É esse aqui!!");
            jBtnConfirmar.setEnabled(false);
            jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jBtnConfirmarActionPerformed(evt);
                }
            });

            jBtnCancelar.setText("Falha no engano :(");
            jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jBtnCancelarActionPerformed(evt);
                }
            });

            jTblConsulta_Multi.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jTblConsulta_Multi.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTblConsulta_MultiMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    jTblConsulta_MultiMouseEntered(evt);
                }
            });
            jScrollPane4.setViewportView(jTblConsulta_Multi);

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addGap(0, 128, Short.MAX_VALUE)
                            .addComponent(jBtnCancelar)
                            .addGap(18, 18, 18)
                            .addComponent(jBtnConfirmar))
                        .addComponent(jTxtPesquisa_Multi)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTxtPesquisa_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnConfirmar)
                        .addComponent(jBtnCancelar))
                    .addContainerGap())
            );

            javax.swing.GroupLayout jPesquisarLayout = new javax.swing.GroupLayout(jPesquisar.getContentPane());
            jPesquisar.getContentPane().setLayout(jPesquisarLayout);
            jPesquisarLayout.setHorizontalGroup(
                jPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            jPesquisarLayout.setVerticalGroup(
                jPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            setTitle("Aceite de Crédito de ICMS");

            jLabel1.setText("Código");

            jTxtId.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusLost(java.awt.event.FocusEvent evt) {
                    jTxtIdFocusLost(evt);
                }
            });

            jLabel2.setText("Produtor");

            jTxtNomeProdutor.setEnabled(false);

            jLabel3.setText("Data de Emissão");

        }
        catch (Exception e){
        }
        jTxtDataEmissao.setEnabled(false);

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtNomeProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtDataEmissao))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2)
                .addComponent(jTxtNomeProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3)
                .addComponent(jTxtDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1))
        );

        buttonGroup1.add(jRbDeferido);
        jRbDeferido.setSelected(true);
        jRbDeferido.setText("Deferido");

        buttonGroup1.add(jRbIndeferido);
        jRbIndeferido.setText("Indeferido");

        jTxtIE.setEnabled(false);

        jLabel4.setText("Inscrição Estadual");

        jLabel5.setText("Status:");

        jLabel6.setText("Crédito Solicitado");

        jTxtCreditoSolicitado.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtIE, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtCreditoSolicitado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jRbDeferido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRbIndeferido))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRbDeferido)
                .addComponent(jLabel4)
                .addComponent(jTxtIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel6)
                .addComponent(jTxtCreditoSolicitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5)
                .addComponent(jRbIndeferido))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Análise"));

        jLabel7.setText("Informação nº");

        jLabel8.setText("Processo");

        jLabel9.setText("Data");

        jLabel10.setText("Crédito Liberado");

        jLabel11.setText("Período analisado");

        jLabel12.setText("até");

        jLabel13.setText("Percentual aproveitado");

        jLabel14.setText("Vendas");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos Comercializados"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("(+)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("(-)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Limpar");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Crédito por Nota Fiscal"));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton5.setText("Importar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtInformacao, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtDataAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtDtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtDtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtPercentual)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtCreditoLiberado)
                    .addComponent(jTxtVendas)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtInformacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jTxtDataAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTxtCreditoLiberado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTxtDtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jTxtPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTxtVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jButton3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jButton4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton6.setText("Gravar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setText("Cancelar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton6)
                .addComponent(jButton8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTxtPesquisa_MultiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPesquisa_MultiKeyReleased

    }//GEN-LAST:event_jTxtPesquisa_MultiKeyReleased

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        incluiPesquisa();
        jPesquisar.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        jPesquisar.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTblConsulta_MultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseClicked
        jBtnConfirmar.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jTblConsulta_MultiMouseClicked

    private void jTblConsulta_MultiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsulta_MultiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTblConsulta_MultiMouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jPesquisar.setVisible(true);
        jTxtPesquisa_Multi.setText("");
        var_consulta = 2;
        montaLista();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        importaCompras();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        var_consulta = 1;
        jPesquisar.setVisible(true);
        jTxtPesquisa_Multi.setText("");
        montaLista();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTxtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdFocusLost
        var_consulta = 11;
        incluiPesquisa();
    }//GEN-LAST:event_jTxtIdFocusLost

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        vendas = 0.00;
        credito = 0.00;

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            vendas += Double.parseDouble(jTable1.getValueAt(i, 2).toString().replace(".", "").replace(",", "."));
        }
        for (int ii = 0; ii < jTable2.getRowCount(); ii++) {
            credito += Double.parseDouble(jTable2.getValueAt(ii, 4).toString().replace(".", "").replace(",", "."));
        }

        System.out.println("Diferença do Crédito: " + (credito - Double.parseDouble(jTxtCreditoLiberado.getText().replace(".", "").replace(",", "."))));

        boolean resposta = Math.round(credito) == Math.round(Double.parseDouble(jTxtCreditoLiberado.getText().replace(".", "").replace(",", ".")));
        System.out.println("Resposta do crédito: " + resposta);

        if (resposta) {
            resposta = vendas.equals(Double.parseDouble(jTxtVendas.getText().replace(".", "").replace(",", ".")));
            System.out.println("Resposta das vendas: " + resposta);

            if (resposta) {
                // INSIRA OUTRAS VALIDAÇÕES AQUI
            } else {
                JOptionPane.showMessageDialog(null, "Valor da venda total difere da venda calculada nos produtos."
                        + "\nVenda total: " + jTxtVendas.getText() + ""
                        + "\nCrédito informado: " + df.format(vendas));
            }

        } else {
            JOptionPane.showMessageDialog(null, "Valor do crédito total difere do crédito calculado nas notas."
                    + "\nCrédito total: " + df.format(Double.parseDouble(jTxtCreditoLiberado.getText().replace(".", "").replace(",", "."))) + ""
                    + "\nCrédito informado: " + df.format(credito));
        }

        if (resposta) {
            Date data = null;
            Double valor = 0.00;
            try {
                proc.setDeferido(jRbDeferido.isSelected());
                proc.setNro_informacao(jTxtInformacao.getText());
                proc.setNro_processo(jTxtProcesso.getText());

                data = dateIn.parse(jTxtDataAnalise.getText());
                proc.setDtAnalise(data);

                if (jRbDeferido.isSelected()) {

                    if (jTable1.getRowCount() > 0 && jTable2.getRowCount() > 0) {

                        valor = Double.parseDouble(jTxtPercentual.getText().replace(".", "").replace(",", "."));
                        proc.setAproveitamento(valor);

                        valor = Double.parseDouble(jTxtCreditoLiberado.getText().replace(".", "").replace(",", "."));
                        proc.setCreditoLiberado(valor);

                        data = dateIn.parse(jTxtDtInicial.getText());
                        proc.setDtInicial(data);

                        data = dateIn.parse(jTxtDtFinal.getText());
                        proc.setDtFinal(data);

                        valor = Double.parseDouble(jTxtPercentual.getText().replace(".", "").replace(",", "."));
                        proc.setAproveitamento(valor);

                        valor = Double.parseDouble(jTxtVendas.getText().replace(".", "").replace(",", "."));
                        proc.setVendas(valor);

                        //INSERE VENDAS
                        for (int x = 0; x < jTable1.getRowCount(); x++) {

                            String idVenda, produtoVenda, valorVenda;
                            idVenda = jTxtId.getText();
                            produtoVenda = jTable1.getValueAt(x, 0).toString();
                            valorVenda = jTable1.getValueAt(x, 2).toString().replace(".", "").replace(",", ".");

                            if (x == 0) {
                                resposta = proc.gravaVendas(true, "('" + idVenda + "','" + produtoVenda + "','" + valorVenda + "')");
                            } else {
                                resposta = proc.gravaVendas(false, "('" + idVenda + "','" + produtoVenda + "','" + valorVenda + "')");
                            }

                        }

                        //INSERE COMPRAS
                        for (int y = 0; y < jTable2.getRowCount(); y++) {
                            String nfCompra, creditoCompra, liberadoCompra, percentualCompra;

                            nfCompra = jTable2.getValueAt(y, 2).toString();
                            creditoCompra = jTable2.getValueAt(y, 3).toString();
                            liberadoCompra = jTable2.getValueAt(y, 4).toString();
                            percentualCompra = jTable2.getValueAt(y, 5).toString();

                            if (y == 0) {
                                resposta = proc.gravaCompras(true, nfCompra, creditoCompra, liberadoCompra, percentualCompra);
                            } else {
                                resposta = proc.gravaCompras(false, nfCompra, creditoCompra, liberadoCompra, percentualCompra);
                            }

                        }

                        if (resposta) {
                            if (proc.atualizaDados()) {
                                JOptionPane.showMessageDialog(this, "Processo atualizado com sucesso!");
                                limpaCampos();
                            } else {
                                JOptionPane.showMessageDialog(this, "Não foi possível atualizar o processo!");
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Tabela de Vendas ou Tabela de Compras não estão preenchidas.");
                    }
                } else {
                    if (proc.atualizaDados()) {
                        JOptionPane.showMessageDialog(this, "Processo atualizado com sucesso!");
                        limpaCampos();
                    } else {
                        JOptionPane.showMessageDialog(this, "Não foi possível atualizar o processo!");
                    }
                }
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, ex);
            } finally {

            }
        }


    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel lista = (DefaultTableModel) jTable1.getModel();
        int linha = jTable1.getSelectedRow();

        lista.removeRow(linha);

    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JFrame jPesquisar;
    private javax.swing.JRadioButton jRbDeferido;
    private javax.swing.JRadioButton jRbIndeferido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTblConsulta_Multi;
    private javax.swing.JTextField jTxtCreditoLiberado;
    private javax.swing.JTextField jTxtCreditoSolicitado;
    private javax.swing.JTextField jTxtDataAnalise;
    private javax.swing.JTextField jTxtDataEmissao;
    private javax.swing.JTextField jTxtDtFinal;
    private javax.swing.JTextField jTxtDtInicial;
    private javax.swing.JTextField jTxtIE;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtInformacao;
    private javax.swing.JTextField jTxtNomeProdutor;
    private javax.swing.JTextField jTxtPercentual;
    private javax.swing.JTextField jTxtPesquisa_Multi;
    private javax.swing.JTextField jTxtProcesso;
    private javax.swing.JTextField jTxtVendas;
    // End of variables declaration//GEN-END:variables

    private DefaultTableModel montaTblProdutos() {
        DefaultTableModel lista = (DefaultTableModel) jTable1.getModel();

        lista.setRowCount(0);
        lista.setColumnCount(0);

        lista.addColumn("codigo");
        lista.addColumn("Produto");
        lista.addColumn("Valor");

        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(90);
        jTable1.getColumnModel().getColumn(2).setMinWidth(90);
        jTable1.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(90);
        jTable1.getTableHeader().getColumnModel().getColumn(2).setMinWidth(90);

        jTable1.setDefaultRenderer(Object.class, new ColorRender());
        
        return lista;
    }

    private DefaultTableModel montaTblNotas() {
        DefaultTableModel lista = (DefaultTableModel) jTable2.getModel();

        lista.setRowCount(0);
        lista.setColumnCount(0);

        lista.addColumn("cod_emitente");
        lista.addColumn("Emitente");
        lista.addColumn("NF");
        lista.addColumn("Crédito");
        lista.addColumn("Liberado");
        lista.addColumn("%");

        jTable2.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable2.getColumnModel().getColumn(0).setMinWidth(0);
        jTable2.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        jTable2.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        jTable2.getColumnModel().getColumn(2).setMaxWidth(80);
        jTable2.getColumnModel().getColumn(2).setMinWidth(80);
        jTable2.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(80);
        jTable2.getTableHeader().getColumnModel().getColumn(2).setMinWidth(80);
        jTable2.getColumnModel().getColumn(3).setMaxWidth(80);
        jTable2.getColumnModel().getColumn(3).setMinWidth(80);
        jTable2.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(80);
        jTable2.getTableHeader().getColumnModel().getColumn(3).setMinWidth(80);
        jTable2.getColumnModel().getColumn(4).setMaxWidth(80);
        jTable2.getColumnModel().getColumn(4).setMinWidth(80);
        jTable2.getTableHeader().getColumnModel().getColumn(4).setMaxWidth(80);
        jTable2.getTableHeader().getColumnModel().getColumn(4).setMinWidth(80);
        jTable2.getColumnModel().getColumn(5).setMaxWidth(50);
        jTable2.getColumnModel().getColumn(5).setMinWidth(50);
        jTable2.getTableHeader().getColumnModel().getColumn(5).setMaxWidth(50);
        jTable2.getTableHeader().getColumnModel().getColumn(5).setMinWidth(50);
        
        jTable2.setDefaultRenderer(Object.class, new ColorRender());

        return lista;
    }

    private void montaLista() {

        DefaultTableModel lista = (DefaultTableModel) jTblConsulta_Multi.getModel();

        lista.setColumnCount(0);
        lista.setRowCount(0);

        switch (var_consulta) {

            case 1:
                lista.addColumn("Id");
                lista.addColumn("Nome");
                lista.addColumn("Processo");

                jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(60);

                sql = "SELECT a.id, b.nome, c.inscri_est, "
                        + "a.dt_inicio_processo FROM produtor_icms a "
                        + "left join cad_pessoas b on (b.id = a.id_produtor) "
                        + "left join icms_estabelecimentos c on (c.id = a.id_estabelecimento) "
                        + " ORDER BY b.nome";
                if (cn.conecta()) {
                    try {
                        cn.executeConsulta(sql);
                        while (cn.rs.next()) {

                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("nome"),
                                "Processo da I.E. " + cn.rs.getString("inscri_est") + " iniciado em " + dateIn.format(cn.rs.getDate("dt_inicio_processo"))
                            });
                        }
                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(null, "Erro ao consultar o banco de dados: " + ex);
                    } finally {
                        cn.desconecta();
                    }
                }
                break;

            case 2:

                lista.addColumn("Código");
                lista.addColumn("Descrição");

                jTblConsulta_Multi.getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getColumnModel().getColumn(0).setMinWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(60);
                jTblConsulta_Multi.getTableHeader().getColumnModel().getColumn(0).setMinWidth(60);

                sql = "SELECT * FROM icms_produtos WHERE uf = 'SC' ORDER BY descricao;";
                if (cn.conecta()) {
                    try {
                        cn.executeConsulta(sql);
                        while (cn.rs.next()) {
                            lista.addRow(new String[]{
                                cn.rs.getString("id"),
                                cn.rs.getString("descricao")
                            });
                        }
                    } catch (Exception e) {
                    } finally {
                        cn.desconecta();
                    }
                }
                break;
        }

    }

    private void incluiPesquisa() {
        int linha = jTblConsulta_Multi.getSelectedRow();

        switch (var_consulta) {
            case 1:

                jTxtId.setText(jTblConsulta_Multi.getValueAt(linha, 0).toString());

            case 11:
                String id = jTxtId.getText();
                proc.carregaDados(id);
                jTxtNomeProdutor.setText(proc.getNomeProdutor());
                jTxtDataEmissao.setText(dateIn.format(proc.getDtEmissao()));
                jTxtIE.setText(proc.getInscricaoEstadual());
                jTxtCreditoSolicitado.setText(df.format(proc.getCreditoSolicitado()).replace(".", "").replace(",", ""));
                if (proc.isDeferido()) {
                    jRbDeferido.setSelected(true);
                } else {
                    jRbIndeferido.setSelected(true);
                }
                jTxtProcesso.setText(proc.getNro_processo());
                jTxtInformacao.setText(proc.getNro_informacao());
                try {
                    jTxtDataAnalise.setText(dateIn.format(proc.getDtAnalise()));
                    jTxtDtInicial.setText(dateIn.format(proc.getDtInicial()));
                    jTxtDtFinal.setText(dateIn.format(proc.getDtFinal()));
                } catch (Exception e) {
                    jTxtDataAnalise.setText("  /  /    ");
                    jTxtDtInicial.setText("  /  /    ");
                    jTxtDtFinal.setText("  /  /    ");
                }
                jTxtCreditoLiberado.setText((df.format(proc.getCreditoLiberado())).replace(".", "").replace(",", ""));
                jTxtPercentual.setText((df.format(proc.getAproveitamento())).replace(".", "").replace(",", ""));
                jTxtVendas.setText((df.format(proc.getVendas())).replace(".", "").replace(",", ""));
                gravar = proc.isAnalisado();

                montaTblNotas();
                montaTblProdutos();
                if (proc.isAnalisado()) {
                    importaCompras();
                    importaVendas();
                }

                break;

            case 2:
                DefaultTableModel lista = (DefaultTableModel) jTable1.getModel();
                String codigo;
                String produto = jTblConsulta_Multi.getValueAt(linha, 1).toString();
                Double valor;

                try {
                    valor = Double.parseDouble(JOptionPane.showInputDialog(this, "Informe o total da venda\npara o produto " + produto + ": ", null).replace(".", "").replace(",", "."));
                    lista.addRow(new String[]{
                        jTblConsulta_Multi.getValueAt(linha, 0).toString(),
                        produto,
                        df.format(valor)
                    });
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Valor informado não é um número válido.", "Vendas por produtos", JOptionPane.ERROR_MESSAGE);
                    valor = 0.00;
                }

                vendas += valor;

                break;

        }
    }

    private void importaCompras() {
        int resposta;

        if (proc.isAnalisado()) {
            resposta = 0;
        } else {
            resposta = JOptionPane.showConfirmDialog(this, "Importar as notas excluirá todas as informações anteriormente digitadas."
                    + "\nDeseja realmente continuar?", "Importação de Notas", JOptionPane.YES_NO_OPTION);
        }

        if (resposta == 0) {
            DefaultTableModel lista = (DefaultTableModel) jTable2.getModel();
            montaTblNotas();

            sql = "SELECT * FROM controladoria.produtor_icms_notas a "
                    + "LEFT JOIN controladoria.cad_pessoas b on (a.id_emitente = b.id) "
                    + "WHERE a.id = '" + jTxtId.getText() + "' "
                    + "ORDER BY a.dt_emissao, a.nro_nf, b.nome ";

            if (cn.conecta()) {
                try {
                    cn.executeConsulta(sql);
                    while (cn.rs.next()) {

                        String notaFiscal = cn.rs.getString("nro_nf");

                        Double vlr_credito = 0.00;
                        Double vlr_liberado = 0.00;
                        Double vlr_percentual = 0.00;

                        if (proc.isAnalisado()) {
                            vlr_credito = cn.rs.getDouble("vlr_credito");
                            vlr_liberado = cn.rs.getDouble("vlr_liberado");
                            vlr_percentual = cn.rs.getDouble("percentual");
                        } else {
                            try {
                                vlr_credito = Double.parseDouble(JOptionPane.showInputDialog(this, "Informe o total do crédito\ndisponibilizado para a Nota Fiscal " + notaFiscal + ": ", null).replace(".", "").replace(",", "."));
                                vlr_liberado = Double.parseDouble(JOptionPane.showInputDialog(this, "Informe o total do crédito\nliberado para a Nota Fiscal " + notaFiscal + ": ", null).replace(".", "").replace(",", "."));
                                vlr_percentual = Double.parseDouble(JOptionPane.showInputDialog(this, "Informe o percentual do aproveitamento mensal\nautorizado para a Nota Fiscal " + notaFiscal + ": ", null).replace(".", "").replace(",", "."));
                            } catch (Exception e) {
                            }
                        }

                        lista.addRow(new String[]{
                            cn.rs.getString("a.id_emitente"),
                            cn.rs.getString("b.nome"),
                            notaFiscal,
                            df.format(vlr_credito),
                            df.format(vlr_liberado),
                            df.format(vlr_percentual)
                        });

                        credito += vlr_liberado;

                    }
                } catch (Exception e) {
                } finally {
                    cn.desconecta();
                }

            }

        } else {
            JOptionPane.showMessageDialog(this, "Importação cancelada!\nA tabela de notas fiscais não será alterada.", "Importação de notas", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void limpaCampos() {
        jTxtId.setText("");
        jTxtNomeProdutor.setText("");
        jTxtDataEmissao.setText("");
        jTxtIE.setText("");
        jTxtCreditoSolicitado.setText("");
        jTxtInformacao.setText("");
        jTxtProcesso.setText("");
        jTxtDataAnalise.setText("");
        jTxtCreditoLiberado.setText("");
        jTxtDtInicial.setText("");
        jTxtDtFinal.setText("");
        jTxtPercentual.setText("");
        jTxtVendas.setText("");

        montaTblNotas();
        montaTblProdutos();
    }

    private void importaVendas() {
        DefaultTableModel lista = (DefaultTableModel) jTable1.getModel();
        montaTblProdutos();

        sql = "SELECT * FROM controladoria.produtor_icms_vendas a "
                + "LEFT JOIN controladoria.icms_produtos b ON (b.id = a.produto) "
                + "WHERE a.id = '" + jTxtId.getText() + "';";
        if (cn.conecta()) {
            try {
                cn.executeConsulta(sql);
                while (cn.rs.next()) {
                    lista.addRow(new String[]{
                        cn.rs.getString("produto"),
                        cn.rs.getString("descricao"),
                        df.format(cn.rs.getDouble("valor"))
                    });
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                cn.desconecta();
            }
        }
    }
}
